components/input_drivers/include/touchpad_input.hpp

* Breaking changes to partition API in latest esp 5.x, so update esp_littlefs component accordingly.
* Touchpad input had erroneous address check (from older version of the component) which triggered a build error for invalid address check on latest gcc. removed the address check.
If you're using the latest ESP-IDF, you'd still like to be able to use these components...
Building samples with the latest esp-idf.

Update for building under latest ESP IDF

---

components/math/example/main/math_example.cpp

Added missing update to math example.
For #35

example: update math example

---

components/socket/include/socket.hpp

bugfix(socket): added missing include

---

components/color/include/color.hpp

* Added equality and inequality operators for espp::Rgb and espp::Hsv
It's nice to be able to compare colors with each other.

feat(color): added equality operators

---

components/state_machine/example/main/CMakeLists.txt
components/state_machine/example/main/Complex_event_data.hpp
components/state_machine/example/main/Complex_generated_states.cpp
components/state_machine/example/main/Complex_generated_states.hpp
components/state_machine/example/main/Complex_metadata.json
components/state_machine/example/main/hfsm_example.cpp
components/state_machine/include/deep_history_state.hpp
components/state_machine/include/shallow_history_state.hpp
components/state_machine/include/state_base.hpp

* Updated state machine example to use latest generated API including functions for sleeping until there are events
* Updated state machine example to always run hfsm in separate thread and to have example / documentation for tick function
* Updated generated code in example
Shows use of new generated code after:
* https://github.com/finger563/webgme-hfsm/pull/150
* https://github.com/finger563/webgme-hfsm/pull/151
* https://github.com/finger563/webgme-hfsm/pull/152
Building and running the example on an ESP32.

feat(state_machine): update example

---

components/ndef/include/ndef.hpp

* Add public address type to mac address field
* Add flags EIR and update eir to handle flags field
Fixes issue with adding EIR Flags field and produces working BLE OOB pairing record.
Tested as part of https://github.com/finger563/esp-nfc-pairing-example/pull/1
See https://github.com/finger563/esp-nfc-pairing-example/pull/1

fix(ndef): flesh out ble oob ndef record

---

.github/workflows/build.yml

ci: update esp-idf in GH action to be 5.1 instead of 5.0

---

components/ads7138/include/ads7138.hpp
components/controller/include/controller.hpp

* Fix use of std::accumulate in ads7138
* Fix use of std::accumulate in controller
Fixes same bug as #138 that was introduced as part of #137 
Building the examples.

fix: Update std::accumulate use

---

components/max1704x/include/max1704x.hpp

Allows you to dynamically allocate (e.g. with `std::shared_ptr`) a Max1704x object.
In the esp-cpp/esp-box-emu project

fix(max1704x): remove unused and unimplemented destructor

---

components/gt911/include/gt911.hpp

Fixes static analysis error introduced in #145

fix: static analysis for gt911

---

components/monitor/CMakeLists.txt

fix(monitor): fix monitor priv_requires tabulate to be public

---

.github/workflows/build_and_publish_docs.yml

fix(doc): add missing folder creation

---

components/ble_gatt_server/include/device_info_service.hpp

* Add structures and APIs for more easily configuring the device information service
Allows a more structured API for configuring the device information service.
Building the ble_gatt_server example.

feat(ble_gatt_server): additional APIs for device info service

---

components/i2c/example/main/Kconfig.projbuild
components/i2c/example/main/i2c_example.cpp

example(i2c): update example for menuconfig of i2c clock speed

---

components/math/example/main/math_example.cpp
components/math/include/fast_math.hpp

* Add lerp for linearly interpolating between two values a,b at t
* Add inv_lerp for inverse linear interpolating to find the t value representing value v between the range specified by a,b
* Add piecewise_linear for performing piecewise linear interpolation of a value in one set of points to a value in another set of points.
* Update math example to test lerp, inv_lerp, and piecewise_linear
Lerp, inverse lerp, and piecewise linear interpolation are useful functions that have a broad range of applicability, so not having to rewrite them reduces the changes of bugs and boilerplate code.
Building and running the updated math example on a QtPy ESP32S3.

feat(math): add lerp, inverse lerp, and piecewise_linear functions

---

.github/workflows/static_analysis.yml

Give write permissions to pull requests for the static analysis action.
For contributors who don't have write access to the repo, the action will fail because it cannot create a comment. This PR should hopefully fix that.
It hasn't yet

add pull-requests: write permissions to the static analysis action

---

components/math/include/bezier.hpp
components/math/include/gaussian.hpp
components/math/include/range_mapper.hpp
components/math/include/vector2d.hpp
doc/en/math/fast_math.rst

doc: update math docs to point to examples

---

components/ble_gatt_server/include/ble_gatt_server_menu.hpp

feat(ble_gatt_server): Add log_rssi command to ble gatt server menu

---

components/monitor/include/task_monitor.hpp

If the user enables `CONFIG_FREERTOS_VTASKLIST_INCLUDE_COREID` in menuconfig, then they will be able to retrieve the core the task is pinned to (or -1 for not pinned to a core). If they do not enable this config variable, then core_id will be -2. This allows the user to see what cores the tasks in the system are running on.

feat(monitor): add core_id to task info

---

components/gfps_service/src/nearby_ble.cpp

Revert "fix(gfps): set default pairing capabilities to have mitm set to true"

---

components/ble_gatt_server/include/ble_gatt_server_menu.hpp

Updates the ble menu (CLI) to use the new unpair_all function that was added as part of #223

feat(ble_gatt_server): update menu to use same unpair function that was added as part of #223

---

components/ble_gatt_server/include/ble_gatt_server.hpp
components/ble_gatt_server/include/ble_gatt_server_menu.hpp

* Update esp-nimble-cpp to support return code from NimBLEDevice::deleteAllBonds
* Update ble_gatt_server to check return code from NimBLEDevice::deleteBond(...)
* Update ble_gatt_server_menu to check return code from NimBLEDevice::deleteAllBonds()
Adding and using the return codes allows failures to be detected and appropriate states to be logged.
Building and running the `ble_gatt_server/example` on a QtPy ESP32s3.

feat(ble): return codes from delete bonding

---

components/cli/include/cli.hpp
components/event_manager/src/event_manager.cpp
components/gfps_service/CMakeLists.txt
components/gfps_service/include/gfps_service.hpp
components/gfps_service/src/gfps_service.cpp
components/led/include/led.hpp

* Change `static constexpr char *<name> = "<string>"` to `static std::string <name>;`
* Memset structures to 0 and manually set fields
* Add missing initializers
* Add [[maybe_unused]]
* Disable some warnings on nearby (external) library
Library warnings make it harder for developers to find / understand any compilation problems or warnings that may arise from their code. Fixing warnings from our components enables cleaner builds and streamlines development.
Building and running in a complex project with many of these components together.

chore: cleanup warnings from components during compilation

---

components/joystick/include/joystick.hpp

* Fix the circular joystick implementation which had a discontinuity when transitioning through the deadzone radius.
Similar to #229 we should not have discontinuities when moving through the output range. This PR ensures that all values within the output range are possible, whereas before any value within the output range whose magnitude was less than the deadzone radius would be clipped and impossible.
Building and running on a device with a joystick and validating that the deadzone for the joystick still works, but values less than the deadzone radius are possible outputs.

fix(joystick): remove discontinuity at deadzone

---

components/gfps_service/src/gfps_service.cpp

Closes https://github.com/esp-cpp/espp/issues/238.

Adds missing `CONFIG_BT_NIMBLE_ENABLED` check

---

components/nvs/example/main/nvs_example.cpp

doc: fix nvs example case sensitivity

---

components/motorgo-mini/include/motorgo-mini.hpp

* Allows motorgo to be initialized with out initializing both motors and both encoders.
* Adds APIs for initializing each motor channel separately.
* Updates to ensure that std::shared_ptr does not delete the objects which are not owned by the pointers.
Enables more complex use cases and use-cases which only have a single motor or need delayed initialization for some reason.
Building and running within `esp-cpp/software-defined-haptics` project.

feat(motorgo): Add APIs for more customized use (single motor, delayed motor init, etc.)

---

components/gt911/example/README.md
components/gt911/example/main/gt911_example.cpp
components/gt911/include/gt911.hpp

* Refactor `gt911::update` to read the keys.
We didn't have support for the home button input on gt911, which meant that the home button on the ESP32-S3-BOX-3 didn't work. This fixes that.
* Building and running `gt911/example` on both T-Deck and ESP32-S3-BOX-3.

feat(gt911): add support for reading home button

---

components/display/include/display.hpp

Allow configuration of display task using `espp::Task::BaseConfig`.
Allows users to change the name, core id, etc. for the display task.
Building the display_drivers/example and building and running in esp-box-emu project.

feat(display): Allow full configuration of display task

---

.github/workflows/build.yml
.github/workflows/build_and_publish_docs.yml

* Update `build.yml` to use `checkout@v4` to remove deprecation warnings.
* Update `build_and_publish_docs.yml` to use pandoc/latex container and to ignore pdflatex command return code
Fixes the build/publish doc action which was failing.
Using the workflow-dispatch command to manually trigger the workflow on this branch.

Fix pdf build

---

components/ble_gatt_server/include/ble_gatt_server.hpp
components/ble_gatt_server/include/ble_gatt_server_menu.hpp

* Updated esp-nimble-cpp submodule to match upstream (which now has changes applied)
* Update ble gatt server and menu to use newer versions of the APIs for the client connection setting / clearing and return type of deleteAllBonds
We upstreamed our changes from esp-cpp/esp-nimble-cpp into h2zero/esp-nimble-cpp, and in doing so slightly changed the APIs. This PR updates to the latest esp-cpp/esp-nimble-cpp which is sync-ed with upstream and updates the espp::BleGattServer and associated CLI menu to use the updated APIs. This will help us stay up to date with esp-nimble-cpp upstream as new bugfixes / features are developed.
Associated PRS that were merged from our fork:
* https://github.com/h2zero/esp-nimble-cpp/pull/158
* https://github.com/h2zero/esp-nimble-cpp/pull/157
* …

Update esp-nimble-cpp to match upstream

---

components/nvs/example/main/nvs_example.cpp
components/nvs/include/nvs.hpp
components/nvs/include/nvs_errc.hpp
components/nvs/include/nvs_handle_espp.hpp

* Move error codes out of nvs/nvs_handle headers and into nvs_errc.hpp
* Rename `espp::NVSHandle` -> `espp::NvsHandle`
* Add `espp::NvsHandle::get(key, value, default, error_code)` which allows a get_or_set paradigm to configure default if no value is present
* Refactor `espp::Nvs` to use `espp::NvsHandle` which greatly simplifies `espp::Nvs` and allows for maximum code reuse.
After #257 we had duplicated code for managing nvs stored data. That PR provided a nice `espp::NvsHandle` implementation, which could be used to replace and simplify the implementation of `espp::Nvs`. 
This PR performs that refactor, and updates the `espp::NvsHandle` to have all the necessary overloads to do so.
Building and running the `nvs/example` on a QtPy ESP32S3 and rebooting it through enough cycles to erase …

feat(nvs): refactor espp::Nvs to use espp::NvsHandle

---

components/file_system/example/README.md
components/file_system/example/main/file_system_example.cpp
components/file_system/include/file_system.hpp
components/file_system/src/file_system.cpp

* Adds convenience methods for removing a file or directory (taking `std::filesystem::path`) as well as for removing the contents of a directory (but not the directory iteself)
* Updates example to show use of the new methods
Current filesystem required you to manually iterate through all the contents of a directory and remove them manually (and you had to properly use `unlink` or `rmdir` depending on the type).
This simplifies use by providing some nice convenience functions on `std::filesystem::path`.
Building and running `file_system/example` on QtPy ESP32s3.

feat(file_system): Add remove(path) and remove_contents(path)

---

components/file_system/example/README.md
components/file_system/example/files/dir1/file3.txt
components/file_system/example/files/dir1/sub1/file2.txt
components/file_system/example/files/dir2/file4.txt
components/file_system/example/files/dir3/file5.txt
components/file_system/example/files/file1.txt
components/file_system/example/main/CMakeLists.txt
components/file_system/src/file_system.cpp

* Adds directory of files to example which is built and bundled onto the target
* Fixes minor bug in `espp::FileSystem::list_directory` string output
Often it is useful to pre-populate an embedded file system with data from the host file system. This example now showcases how easy it is to do.
Building and running `file_system/example` on a QtPy ESP32s3.

feat(file_system): Update example to include built+bundled file system

---

components/joystick/include/joystick.hpp
components/math/include/range_mapper.hpp

* Update `espp::Joystick` to clamp the provided deadzones, ensuring they're within the range [0,1]
* Update `espp::Joystick` to add methods for querying the type and the deadzones
* Update `espp::RangeMapper<>` to add methods to query the input distribution
* Update `espp::RangeMapper<>` to ensure the center/range deadbands are always non-negative.
Allows more complex use and reconfiguration of the `espp::Joystick` and the `espp::RangeMapper<>`.
* Building the `math/example`
* Building the `joystick/example`

feat: Add APIs to `espp::RangeMapper<>` and `espp::Joystick` for getting their configs

---

components/esp-box/include/esp-box.hpp

feat(esp-box): expose mute pin / gpio via getter for use

---

components/math/example/main/math_example.cpp

Add additional examples of using the piecewise linear functions - including one with a discontinuity.
More examples provide better ways of testing the code and showcasing how it can be used for people.
Building and running the `math/example` on a QtPy ESP32s3.
[piecewise_linear.xlsx](https://github.com/user-attachments/files/16112833/piecewise_linear.xlsx)
[piecewise_linear.csv](https://github.com/user-attachments/files/16112834/piecewise_linear.csv)

example(math): Add additional piecewise linear examples

---

components/rtsp/include/rtp_packet.hpp

fix(rtsp): Fix maybe-uninitialized errors in RtpPacket

---

components/motorgo-mini/CMakeLists.txt
components/motorgo-mini/example/main/motorgo_mini_example.cpp
components/motorgo-mini/include/motorgo-mini.hpp
components/motorgo-mini/src/motorgo-mini.cpp

* Move implementation of `espp::MotorGoMini` class from `hpp` into `cpp`
* Switch `espp::MotorGoMini` to be a singleton class with a `get()` method, more like the other hardware abstraction / support components.
* Remove some unneeded protected methods, since they're better provided by the public API.
Similar to the other HAL, you really can only run the code on a single MotorGoMini, so it might as well be a singleton.
Building the example

feat(motorgo-mini): Update to be singleton. Moved impl to cpp

---

components/esp-box/CMakeLists.txt
components/esp-box/Kconfig
components/esp-box/example/README.md
components/esp-box/example/main/esp_box_example.cpp
components/esp-box/include/esp-box.hpp
components/esp-box/src/esp-box.cpp
components/matouch-rotary-display/CMakeLists.txt
components/matouch-rotary-display/example/README.md
components/matouch-rotary-display/include/matouch-rotary-display.hpp
components/matouch-rotary-display/src/matouch-rotary-display.cpp
components/t-deck/CMakeLists.txt
components/t-deck/Kconfig
components/t-deck/example/README.md
components/t-deck/example/main/t_deck_example.cpp
components/t-deck/include/t-deck.hpp
components/t-deck/src/t-deck.cpp

* Fix unimplemented methods in `esp-box`, `matouch-rotary-display`, `t-dongle-s3`, `t-deck`
* Update `esp-box`, `t-deck` to use interrupt for touch input
* Update examples for `esp-box`, `matouch-rotary-display`, `t-deck` to use `std::deque` for managing circles 
* Improves feeling of touchscreen and adds example use of interrupts
* Ensures all methods are fleshed out
Building and running those examples on those hardware.
ESP-BOX:
https://github.com/esp-cpp/espp/assets/213467/d5379983-9bc2-4d56-a9fc-9e37f54af15e
T-DECK:
https://github.com/esp-cpp/espp/assets/213467/dc476c3d-dd9e-4b65-8c2d-9eda3ff3f33f
MATOUCH-ROTARY-DISPLAY:
https://github.com/esp-cpp/espp/assets/213467/4d88dd97-b23a-49d0-b6a2-2ee3b50a8f62

Update `esp-box`, `t-deck`, `matouch-rotary-display` examples

---

components/led/include/led.hpp

fix(led): Only install LED ISR once

---

components/t_keyboard/include/t_keyboard.hpp

feat(t_keyboard): Update so read (no task) updates pressed key state

---

.github/workflows/static_analysis.yml

ci: Update static analysis to use v4 of checkout

---

components/display/include/display.hpp
components/display_drivers/example/main/display_drivers_example.cpp
components/display_drivers/include/gc9a01.hpp
components/display_drivers/include/ili9341.hpp
components/display_drivers/include/st7789.hpp
components/display_drivers/src/gc9a01.cpp
components/display_drivers/src/ili9341.cpp
components/display_drivers/src/st7789.cpp
components/esp-box/include/esp-box.hpp
components/esp-box/src/esp-box.cpp
components/matouch-rotary-display/example/main/matouch_rotary_display_example.cpp
components/matouch-rotary-display/src/matouch-rotary-display.cpp

#282 Added some new functionality, but the new `mutex` and `swap_xy` in the display drivers were inline - this fixes that.
These broke static analysis and are not recommended practice.
This PR :)

fix(display_drivers): fix inline declaration for swap_xy and mutex

---

components/encoder/include/abi_encoder.hpp

chore(encoder): Simplify to use requires(...) instead of enable_if

---

components/color/example/main/color_example.cpp
components/color/include/color.hpp
components/color/src/color.cpp
components/math/include/gaussian.hpp

* Add assignment operator to `espp::Rgb` and `espp::Hsv` to allow converting assignment between the two
* Add `color_code` static methods for generating color code from rgb and hsv values.
Simplifies API / use of `Rgb` and `Hsv` color classes.
Building and running the color example.

feat(color): add converting assignment operator for Rgb <-> Hsv

---

components/input_drivers/include/keypad_input.hpp

* Update keypad_input to use new lvgl v9 methods for initializing keypad input
After #265, the keypad input wasn't updated, so this does that. This is needed for [esp-box-emu](https://github.com/esp-cpp/esp-box-emu) to update to lvgl v9
In that project

fix(keypad input): update keypad input to lvgl v9

---

components/timer/example/main/timer_example.cpp
components/timer/include/timer.hpp
components/timer/src/timer.cpp

* Add `espp::Timer::AdvancedConfig` which allows specification using `Task::BaseConfig`
* Update timer example to show use of advanced config
* Allows use of Task::BaseConfig for API symmetry
Building and running the timer/example on a QtPy ESP32s3.

feat(timer): Add advanced config reusing Task::BaseConfig

---

components/joystick/CMakeLists.txt
components/joystick/include/joystick.hpp
components/joystick/include/joystick_formatters.hpp
components/joystick/src/joystick.cpp
components/math/include/vector2d.hpp
components/ndef/include/ndef.hpp
components/pid/include/pid.hpp
components/pid/include/pid_formatters.hpp
lib/autogenerate_bindings.py
lib/espp.cmake
lib/include/espp.hpp
lib/pyproject.toml
lib/python_bindings/espp/__init__.pyi
lib/python_bindings/pybind_espp.cpp

* Add `joystick`, `ndef`, and `pid` components to c++/python cross-platform library
* Update component code to support litgen better: add explicit scoping and move some implementation to source files
The more code is exposed to the cross-platform library, the more useful it will be to people and the more thoroughly it can be tested.
Building the cross-platform library and running the c++ and python tests.

Update python bindings to add `joystick`, `ndef`, and `pid`

---

components/base_peripheral/include/base_peripheral.hpp

* Add overloads to read/write which take `std::vector<uint8_t>`
* Add overloads to `set_bits` and `clear_bits` which take `std::bitset<8>`
* Add `toggle_bits()` functions 
Adds additional utility functions to the API so that developers / subclasses have to do less work.
Building the examples in CI.

feat(base_peripheral): Add additional apis using `std::vector` and `std::bitset`. Add `toggle_bits()` functions as well.

---

components/esp32-timer-cam/include/esp32-timer-cam.hpp
components/esp32-timer-cam/src/esp32-timer-cam.cpp

* Convert battery voltage to actual battery volts instead of raw voltage divider millivolts
* Add pin definitions for camera

feat(esp32-timer-cam): Add battery voltage scale and camera pin defs

---

components/task/include/task.hpp
components/timer/example/main/timer_example.cpp
components/timer/include/high_resolution_timer.hpp
components/timer/include/timer.hpp
components/timer/src/high_resolution_timer.cpp
components/timer/src/timer.cpp

* Add `start_/stop_watchdog()` to `Timer` and `HighResolutionTimer` classes
* Move `HighResolutionTimer` implementation from header to source file.
* Update `timer/example` to demonstrate / test the new methods and functionality.
Similar to #322, we'd like to be able to monitor the execution of our `Timer`s and `HighResolutionTimer`s.
Building and running `timer/example` on a QtPy ESP32s3.
Timer:
HighResolutionTimer:

feat(timer): Update `Timer` and `HighResolutionTimer` to have `start_watchdog()` and `stop_watchdog()` methods

---

components/esp-box/src/audio.cpp

fix(esp-box): add missing IRAM_ATTR to tx_sent_callback

---

components/ble_gatt_server/example/main/ble_gatt_server_example.cpp
components/ble_gatt_server/include/ble_gatt_server.hpp
components/ble_gatt_server/include/ble_gatt_server_callbacks.hpp
components/ble_gatt_server/src/ble_gatt_server.cpp
components/ble_gatt_server/src/ble_gatt_server_callbacks.cpp
components/gfps_service/src/nearby_ble.cpp
components/hid_service/example/main/hid_service_example.cpp

* Update esp-nimble-cpp submodule to latest `main` which matches upstream
* Update `ble_gatt_server`, `gfps_server`, components
* Update affected examples
* Keeps our submodule up to date with latest, ensuring compatibility and maintainability
This is a minor breaking change to the underlying `esp-nimble-cpp` API, which makes a small change to the name so that `NimBLEDevice::injectConfirmPIN` -> `NimBLEDevice::injectConfirmPasskey`.
* Building `ble_gatt_server/example`, `gfps_service/example`, and `hid_service/example`

feat(ble): Update esp-nimble-cpp to latest upstream for API refactor

---

components/ble_gatt_server/include/ble_gatt_server.hpp

* Update esp-nimble-cpp submodule to have new server-client code
* Update `BleGattServer` to remove extra `client` pointer used for getting name / rssi from connected clients, instead using the new client that is managed within the server itself.
* Simplifies the `BleGattServer`
* Keeps `esp-nimble-cpp` up to date for compatibility and maintenance
Building and running `hid_service/example` on QtPy ESP32s3 and testing with iPhone

feat(ble): Update esp-nimble-cpp and simplify BleGattServer

---

components/hid_service/example/main/hid_service_example.cpp
components/hid_service/include/hid_service.hpp

* Update `hid_service` to store the input, output, and feature report characteristics together with their report ID in vectors within the class and return references to them if the same report id is requested again. 
* Update the example to test these methods to ensure they work as intended.
This ensures that memory is not leaked creating duplicate characteristics
Building and running `hid_service/example` on QtPy ESP32S3

feat(hid_service): Update to store / reuse report characteristics

---

components/led/include/led.hpp
components/led/src/led.cpp

* Update LED to allow configuration of sleep mode behavior if using ESP-IDF >= 5.4
As of 5.4, if you want your LED to work in sleep mode, you have to explicitly enable it (while still also using a light-sleep enabled clock source). This PR makes it so that that configuration option is configurable from user application code and sets the default to have the LED enabled during light sleep (if the clock source allows). Application code can now choose to disable light sleep LED behavior using the ESP-IDF provided configuration parameter.
* Building and running the `led/example`
* Running in a project with light sleep

feat(led): Update to allow configuration of the led sleep mode

---

components/ble_gatt_server/include/ble_gatt_server.hpp

Make `get_connected_device_name` and `get_connected_device_rssi` take const parameters.

feat(ble_gatt_server): Update `get_connected_device_{name/rssi}` to take const arguments

---

components/qtpy/example/main/qtpy_example.cpp
components/qtpy/include/qtpy.hpp
components/qtpy/src/qtpy.cpp
components/t-dongle-s3/CMakeLists.txt
components/t-dongle-s3/Kconfig
components/t-dongle-s3/example/CMakeLists.txt
components/t-dongle-s3/example/main/t_dongle_s3_example.cpp
components/t-dongle-s3/include/t-dongle-s3.hpp
components/t-dongle-s3/src/t-dongle-s3.cpp

* Add built-in support for configuring the button on the T-Dongle-S3 using the interrupt class, similar to qtpy and others
* Fix docs
* Simplify t dongle s3 example using new button API
Simplifies use of `TDongleS3` and makes it more consistent with other HAL components.
Building and running `t-dongle-s3/example` on a t-dongle-s3 and ensuring the button still works and rotates the display.

feat(t-dongle-s3): Move button into TDongleS3 as interrupt

---

components/hid-rp/include/hid-rp-xbox.hpp

feat(hid-rp): Allow xbox battery report to have data set

---

components/codec/es8311/es8311.cpp
components/display_drivers/include/sh8601.hpp

Try to fix remaining static analysis
Keeps code quality good and ensures PRs don't get a lot of bad analysis from unrelated code.
This PR.

fix more static analysis

---

components/joystick/example/main/joystick_example.cpp
components/joystick/src/joystick.cpp

* Update to ensure we handle the edge case that `center_deadzone_radius == range_deadzone == 0.5f`.
* Update example to explicitly test large / overlapping deadzones
In the case that center and range deadzone are both 0.5, both of the first conditionals would return false, then magnitude range would be 0.0, leading to div/0 error.
Note: I've not actually seen this error and I cannot actually trigger it even when trying to in my test code. However, It's a small enough change I think it's worth fixing.
This PR fixes it and ensures that there is not a case for which the magnitude_range will be calculated to be 0.
Build and run `joystick/example` on QtPy ESP32-S3 and ensure new test passes
[test1.csv](https://github.com/user-attachments/files/19486638/test1.csv) …

fix(joystick): Update joystick to fix edge case

---

components/t-deck/example/main/t_deck_example.cpp
components/t-deck/include/t-deck.hpp
components/t-dongle-s3/CMakeLists.txt
components/t-dongle-s3/example/main/t_dongle_s3_example.cpp
components/t-dongle-s3/include/t-dongle-s3.hpp
components/t-dongle-s3/src/sdcard.cpp

* Add sdcard (sdmmc) support to `t-dongle-s3` component
* Update sdcard interface for `t-deck` component to have config allowing configuration of the mount parameters
* The `t-dongle-s3` has a pretty nifty little sdcard slot (in the USB-A port) so this allows you to actually use it :)
* Allowing the user to configure the mount parameters for the sdcard reduces compatibility to different use cases
* Build and run `t-dongle-s3/example` on t-dongle-s3 with a uSD card inserted, ensure that the card is properly mounted
* Build and run `t-deck/example` on t-deck with a uSD card inserted, ensure that the card is properly mounted

feat(t-dongle-s3): Add uSD card support

---

components/filters/idf_component.yml

Update `esp-dsp` from `1.3.0` to `1.6.4`
Keeps our dependencies up to date, fixing bugs and adding new features
https://github.com/espressif/esp-dsp/compare/v1.3.0...v1.6.4

chore: Update esp-dsp to 1.6.4

---

components/kts1622/include/kts1622.hpp
components/tla2528/include/tla2528.hpp

* Update `kts1622` to protect all its multi-operation calls with base_mutex_
* Update `tla2528` to ensure all its multi-operation calls are protected similarly
Provides protections against race conditions when used from multiple threads
Build and run `kts1622/example` and `tla2528/example`

fix(kts1622/tla2528): Ensure protection using base_mutex

---

components/ads1x15/src/ads1x15.cpp
components/as5600/include/as5600.hpp
components/aw9523/include/aw9523.hpp
components/bm8563/include/bm8563.hpp
components/drv2605/include/drv2605.hpp
components/ft5x06/include/ft5x06.hpp
components/gt911/include/gt911.hpp
components/max1704x/include/max1704x.hpp
components/mcp23x17/include/mcp23x17.hpp
components/mt6701/include/mt6701.hpp
components/st25dv/include/st25dv.hpp
components/tt21100/include/tt21100.hpp

fix: Ensure peripherals protect calls with multiple operations

---

.gitmodules
lib/CMakeLists.txt
lib/build.ps1
lib/build.sh
lib/cmake/CPM.cmake

* Remove `pybind11` submodule
* Add `CPM.cmake` and use it to fetch pybind11 2.13.6 when building
* Update CMake min version to 3.20
* Update build scripts to use --parallel command to speed up builds
Removes unnecessary submodules - ensuring pybind11 is only ever downloaded if/when you need to build the library.
Running `lib/build.sh`

feat: Remove pybind11 submodule, instead using CMake Package Manager (CPM)

---

components/i2c/example/main/Kconfig.projbuild
components/icm20948/example/main/Kconfig.projbuild
components/icm20948/example/main/icm20948_example.cpp
components/icm20948/include/icm20948.hpp
components/icm20948/src/icm20948.cpp
components/icm42607/example/main/Kconfig.projbuild
components/icm42607/example/main/icm42607_example.cpp
components/icm42607/include/icm42607.hpp

* Add mutex protection to `icm42607` and `icm20948` implementations.
* Update examples a little for clarity
* Update kconfigs a little for proper syntax highlighting (emacs)
Ensures the classes are thread safe.
Building and running the respective examples on dev boards.

fix(imu): Cleanup ICM20948 and ICM42607 to ensure proper mutex protection

---

components/wrover-kit/include/wrover-kit.hpp
components/wrover-kit/src/wrover-kit.cpp

feat(wrover-kit): Backlight is available after initialize_lcd now

---

components/t-dongle-s3/include/t-dongle-s3.hpp
components/t-dongle-s3/src/t-dongle-s3.cpp

feat(t-dongle-s3): Backlight is available after initialize_lcd now

---

components/seeed-studio-round-display/include/seeed-studio-round-display.hpp
components/seeed-studio-round-display/src/seeed-studio-round-display.cpp

feat(seeed-studio-round-display): Backlight is available after initialize_lcd now

---

components/base_peripheral/include/base_peripheral.hpp
components/gfps_service/include/gfps.hpp
components/gfps_service/include/gfps_service.hpp
components/gfps_service/src/nearby_ble.cpp

Ran `pre-commit run --all-files` to let clang format files. 
Every time I ran this to format the files I worked on, I got various other changes. Cleaning that up.

Chore: Ran Pre-commit to format various files
