components/cli/CMakeLists.txt
components/cli/example/CMakeLists.txt

* Added missing requires for `driver` and `vfs` components from espressif to the `cli` component
* Removed the explicit dependency on `driver` and `vfs` components from the `cli/example` since they are now captured by the `cli` component as they should be.
To use the `cli` component, you should only need to depend on the `cli` component - anything it depends on to build/run should be captured in its component dependencies. The example had built successfully because the required dependencies for the cli component were being added to its CMakeLists.txt improperly instead of being in cli/CMakeLists.txt.
* Building and running the `cli/example`

bugfix(cli): add missing requires

---

components/adc/include/continuous_adc.hpp

* Updated ContinuousAdc to create, use, and free calibration data for each channel so that the values returned are actually millivolts instead of raw values like they were.
* Updated continuous adc task debug logger to be rate limited
We expect to get millivolts from the API, not raw values, so this fixes the implementation to actually return calibrated values in millivolts, just like the oneshot adc.
Building and running on a board with an NTC and validating that the temperature measured matches the voltage measured which matches the actual temperature.

bugfix(adc): use calibration data

---

components/cli/include/cli.hpp

* Updated `cli::configure_stdin_stdout()` to support both UART console as well as USB-SERIAL-JTAG consoles (for supporting the native usb serial programming port.
Note: you will need to configure the menuconfig of your project to set the `USB-SERIAL-JTAG` as the default console output port (instead of the secondary output port which is default).
Further Note: you may need to press `enter` once to get the console to show when running under this config if you do not explicitly call `configure_stdin_stdout` at the start of your program.
By default, the VFS is not configured to use the USB-SERIAL-JTAG port for std::cin / std::cout. Similar to how we configured vfs to use standard UART for stdin/stdout we now configure vfs to use the USB-SERIAL-JTAG for stdin/stdout if it was configured via …

feat(cli): added support for usb-serial-jtag console

---

components/ads7138/include/ads7138.hpp

* Fix issue where control reached end of non-void function when configuring the Ads7138 in RAW mode (no oversampling).
If you do not set the oversampling ratio (e.g. by not specifying it in the `Ads7138::Config` struct), then you would get a compile error because control for the `conversion_complete` function would reach the end of the function without a return statement. This fixes that issue by naively returning true.
Compiling with no oversampling configred.

bug(ads7138): fix compile error in RAW mode

---

components/cli/include/cli.hpp

* Updated cli component so that CONFIG_ESP_CONSOLE_UART_NUM is cast to uart_port_t to prevent compiler warning that is treated as an error with latest esp-idf master branch.
With latest compilers installed from esp-idf/master branch (`v5.2-dev-1736-ga2d76ad38a`) the raw use of `CONFIG_ESP_CONSOLE_UART_NUM` results in an error about the use of an `int` as `uart_port_t`. This PR fixes that by adding an explicit cast.
Building the cli example.

bug(cli): fix conversion error

---

components/ads7138/include/ads7138.hpp

* Updated how the functions to get all values are implemented to use the size of analog_inputs_ to set the size of the vector containers for a single allocation instead of using push_back which performs heuristic allocation
No sense performing more allocations (and potentially using more space) than needed.
Building the ads7138 example

refactor(ads7138): updated functions to get all values

---

components/display_drivers/include/display_drivers.hpp

* Updated display drivers component to allow for displays that have no reset pin - defined as GPIO_NUM_NC
Used in https://github.com/esp-cpp/wireless-debug-display/pull/2
See https://github.com/esp-cpp/wireless-debug-display/pull/2

feat(display_drivers): allow for no reset pin

---

components/adc/include/adc_types.hpp

Fixes multiple definition issue when using ADC component in some cases.
Building in a project which exhibited the error and then using this fix to fix it.
Example of the error:

fix(adc): make AdcConfig operators static

---

components/cli/include/line_input.hpp

fix(cli): add missing <atomic> include to line_input.hpp

---

.gitignore
components/timer/include/timer.hpp
lib/build.sh
pc/build.sh

* Update timer to use std::chrono::microseconds for storing period and delay to improve precision of timing across platforms (e.g. on MacOS).
* Add period_float and delay_float members which perform the conversion once to then be printed in logs later as needed.
* feat(x-plat): added build scripts for ease of use and ignore the lib/pc output directory
On MacOS, the existing use of `std::chrono::duration<float>` for the period and delay had odd behavioral issues, leading to no wait at all on the condition variable. This PR fixes that.
* Building and running the timer example on a QtPy ESP32 PICO
* Building and running the PC timer test on MacOS

feat(timer): change period/delay storage

---

components/display_drivers/include/ili9341.hpp

We'd like to be able to use those members of the config struct on ili9341 displays (which use the same init commands as st7789).

feat(ili9341): update ili9341 to use the config mirror_x/mirror_y/swap_xy just like st7789

---

components/adc/include/adc_types.hpp
components/ads7138/include/ads7138.hpp
components/button/include/button.hpp
components/filters/include/butterworth_filter.hpp
components/filters/include/lowpass_filter.hpp
components/filters/include/sos_filter.hpp
components/format/include/format.hpp
components/math/include/range_mapper.hpp
components/tla2528/include/tla2528.hpp

fix(fmt): updated format helpers to explicitly use fmt::format_to to prevent collision with std::format_to if <format> is included (like possible with later idfs)

Format helpers use fmt::format_to to prevent collision with std::format_to if <format> is used 

---

components/format/include/format.hpp
components/tt21100/include/tt21100.hpp

* Update libfmt (fmt) external library to latest
* Added commonly used includes from fmt to format.hpp
Makes it work with the latest esp-idf and supports additional formatting of things such as `std::atomic`.
Building the examples.

Update format for latest gcc and esp-idf

---

components/event_manager/src/event_manager.cpp

* Updated remove_subscriber implementation to use reference when erasing callback from list to ensure that it is properly erased from the shared state
* Added some warnings if removal occurs when topic or component are not found
Fixes a bug where the subscriber callback was not removed when it should have been, leading to the callback being called later.
Building and running within the esp-box-emu project.

fix: subscriber callback not removed

---

components/tla2528/include/tla2528.hpp

* Properly store result of std::accumulate when configuring tla2528 digital i/o and analog inputs
When updating TLA2528 to use `std::accumulate` for #137 static analysis results, I inadvertently introduced a bug which did not properly configure the digital and analog inputs so the peripheral would not function correctly.
* Building the TLA2528 example
* Building and running with TLA2528 component in a different project.

fix(tla2528): fix use of std::accumulate

---

components/display/CMakeLists.txt

Add `led` and `driver` to the list of component requirements for the `display` component.
If you include the `display` or `display_drivers` component, without also including the `led` and `driver` components, then you will get a build failure. This fixes that issue by ensuring that the `display` component (which is used by the `display_drivers` component) directly includes those components.

fix(display): Add missing component requirements to display component

---

components/cli/include/cli.hpp
components/color/src/color.cpp
components/display_drivers/example/main/gui.hpp
components/event_manager/src/event_manager.cpp
components/filters/include/transfer_function.hpp
components/i2c/example/main/i2c_menu.hpp
components/math/include/bezier.hpp
components/math/include/gaussian.hpp
components/math/include/vector2d.hpp
components/rtsp/include/jpeg_frame.hpp
components/rtsp/include/jpeg_header.hpp
components/rtsp/include/rtp_jpeg_packet.hpp
components/rtsp/include/rtp_packet.hpp
components/socket/include/tcp_socket.hpp
components/state_machine/example/main/Complex_generated_states.hpp
components/state_machine/include/deep_history_state.hpp
components/state_machine/include/shallow_history_state.hpp
components/state_machine/include/state_base.hpp

style: re-run new clang format on all files

---

components/ble_gatt_server/include/ble_gatt_server_callbacks.hpp
components/ble_gatt_server/src/ble_gatt_server_callbacks.cpp

* Add preprocessor guards around BleGattServerCallbacks so that the component can be required and included, but optionally disabled if no BLE is needed / used.

feat(ble_gatt_server): add preprocessor guards

---

components/ble_gatt_server/include/ble_gatt_server.hpp
components/ble_gatt_server/include/ble_gatt_server_callbacks.hpp
components/hid_service/include/hid_service.hpp

Add missing `#include <sdkconfig.h>` to ble_gatt_server and `hid_service` components (`gfps_service` already included it)
#175 caused a regression where cloud builds and first builds could fail, but subsequent builds would work. This is caused by missing inclusion of `sdkconfig.h` that this PR fixes.
Building tests in CI on this PR.

fix(ble): added missing sdkconfig include

---

components/ble_gatt_server/src/ble_gatt_server.cpp
components/ble_gatt_server/src/ble_gatt_server_callbacks.cpp
components/ble_gatt_server/src/ble_gatt_server_ext_adv.cpp

fix(ble_gatt_server): fix ble gatt server compile fail when BLE disabled

---

components/logger/CMakeLists.txt
components/logger/include/logger.hpp

* Updated logger component to use the esp_timer component (if ESP_PLATFORM) and the `esp_timer_get_time` function for time since boot in microseconds, using the original std::chrono::steady_clock otherwise.
This allows the time value for logger to take less time to format as well as keeps it synchronized with time since boot (and therefore any other ESP_LOG system logs).
Building and running the logger example.

feat(logger): Use esp_timer_get_time on esp platform

---

components/ble_gatt_server/include/ble_gatt_server.hpp
components/ble_gatt_server/include/ble_gatt_server_menu.hpp
components/hid_service/example/main/hid_service_example.cpp

* Update BleGattServer to have API to get RSSI for a connection info (ConnInfo) and to get the RSSI values for all connected devices, using the Client object
* Update ble gatt server menu to add RSSI printout to connected query, and add a rssi query to return the same, but without the device names
* Update hid_service example to also print out RSSI when a device connects
Getting the RSSI is useful when testing your connection strength, hardware, and for presenting to the user.
Building and running the `hid_service` example on a QtPy ESP32S3.

feat(ble_gatt_server): add API to get RSSI

---

components/task/include/task.hpp

Change `std::string_view name` -> `std::string name` in the task config structures.
Sometimes task names can be garbled because the string holding the data was not properly copied over into the task itself. Changing the task config structure to take a std::string instead of string_view fixes this.

fix(task): update task name config to be string instead of string_view

---

components/button/include/button.hpp
components/interrupt/example/main/interrupt_example.cpp
components/interrupt/include/interrupt.hpp

* Update interrupt component to enable gpio isr to be allocated on a core of the user's choosing
* Update interrupt example to test and verify new implementation
* Update button component for similar purpose if it is an interrupt button.
For a complex system using many interrupts, it may be necessary to move some interrupts over to the second CPU or specifically select the core that you want the different interrupt systems to run on.
Building and running the updated interrupt example on a esp32s3.

feat(interrupt): allow user to configure which core GPIO interrupt is allocated on

---

components/i2c/CMakeLists.txt
components/i2c/include/i2c.hpp

In situations where all non-reserved core 0 interrupt slots are taken, it is helpful to be able to move the I2C interrupts to another core if available.

Add an option to specify the core_id when initializing I2C driver

---

components/math/example/CMakeLists.txt
components/math/example/main/math_example.cpp
components/math/include/vector2d.hpp

* Move equality operator into vector2d class
* Add spaceship (<=>) operator to vector
* Update implementation of scaling operator to work with more than just float scaling of float vectors using auto
* Upadte math example to improve logging / readability (add logger)
* Update math example to test integer vector explicitly
* Update math example to test vector comparison operators explicity for both float and integer vectors
* Update math example to better test piecewise_linear function
* Allows scaling of integer vectors more easily
* Allows math example logs to be visually parsed more easily
* Check comparison operators directly
* Spaceships are cool, so of course the spaceship operator (`<=>`) is cool too.
Building and running the math example on a QtPy ESP32S3.

feat(math): Flesh out vector2d operators

---

components/cli/CMakeLists.txt
components/cli/include/cli.hpp
components/cli/include/line_input.hpp
components/cli/src/cli.cpp

* Refactor `espp::Cli` interface to have additional static functions for configuring the stdin/stdout (or informing the system they've already been configured)
* Update `espp::LineInput` to enable the command and escape sequences to be turned off (default on)
* Update `espp::Cli` to allow prompt and completions to be turned off
The existing `Cli` had a function which automatically configured stdin/stdout for either ESP_CONSOLE_UART or ESP_CONSOLE_USB_SERIAL_JTAG, depending on what was selected in menuconfig. This worked, but did not allow the Cli to work with other interfaces such as a custom UART or a custom CDC (or in general another system mapped through VFS).
Also, if you wanted to enable more machine-managed console input/output, you had no way of turning off the escape sequence and …

feature: Allow Cli to use custom CDC or VFS

---

components/i2c/include/i2c.hpp

This PR fixes a possible timing issue when initializing I2C on a different core.
This change ensures that the I2C init is complete before returning, whereas previously it was up to the caller to ensure enough time has passed. This new automatic behavior should be more robust and less error prone.
NOTE: I also changed the core_id checking logic. In the event a core ID was specified explicitly in a single core usage, it seemed more appropriate to use the direct i2c_driver_install call.

Use condition variable to sync init when using multiple cores

---

components/gfps_service/src/nearby_ble.cpp

Lately, I've seen that the default of `mitm = false` was causing issues with bonding on iOS and Android. Updating this to be `true` fixes that issue.
Long term (in a future PR), I'll update the GFPS interface so that the default settings can be provided via API so they are not hardcoded in here. This will enable more custom integration.
Building and running in a separate (gfps-enabled) project.

fix(gfps): set default pairing capabilities to have mitm set to true

---

components/ble_gatt_server/include/ble_gatt_server.hpp

Add a `BleGattServer::unpair_all()` function which can be used instead of `NimBLEDevice::deleteAllBonds()`.
Related to https://github.com/h2zero/esp-nimble-cpp/issues/155
I found that the `NimBLEDevice::deleteAllBonds()` did not properly clean up the NVS, but that cleaning the bonding info manually (one at a time) did work. This PR adds a convenience function for removing all bonds one by one.

feat(ble_gatt_server): add method for unpairing all devices

---

components/timer/include/high_resolution_timer.hpp

* Delete the `espp::HighResolutionTimer` timer handle in `stop()`, instead of just in the destructor.
When reviewing the code, it was determined that repeated calls to `start(...)` (even if they included `stop()`), would leak memory as `esp_timer_create(...)` was called multiple times without calling `esp_timer_delete(...)`.
This PR fixes that problem by ensuring that `stop()` calls `esp_timer_delete(...)` if the timer_handle is not null.
Building and running the `timer/example` on a QtPy ESP32s3.

fix(timer): Fix memory leak in `espp::HighResolutionTimer` when calling start repeatedly

---

components/math/example/main/math_example.cpp
components/math/include/range_mapper.hpp

* Update range mapper implementation so that the scaling starts at the deadband edge (reduce discontinuities in standard output range)
* Update range mapper implementation to fix bugs arising from comparing to T(0) when it should have instead been comparing against center_ or output_center_
* Update math example to have better range mapper test - and one which outputs csv for easier plotting / checking
* Update range mapper docstrings to have more text and warning about input inversion
Previously the range mapper had some bugs depending on how the input or output distributions were configured (since parts of the code did a test against `T(0)` instead of `center_` (input center) or `output_center_`). Additionally, the deadzone / deadband that was applied around center not only caused the …

fix(math): update range mapper implementation

---

components/monitor/include/task_monitor.hpp

* Fixed bug in task monitor which returned core_id natively, meaning that tskNO_AFFINITY would be returned as a very large number instead of -1. Now it checks that value specifically and converts it to -1 for simpler display
* Simplified cdoe for returning task info since both cases were doing the same thing
Seeing core id in task info printing is helpful for determining processor utilization. A small number (-1) for no core affinity is easier to visually parse than a very large number and is more consistent with the APIs for setting core affinity.
Building and running to print task info.
Example:

fix(monitor): properly display no core affinity as -1

---

components/monitor/include/task_monitor.hpp

* Update task monitor to support dynamically configuring table column width based on configured freertos max name length
* Update task monitor to not show core id column if core id is not configured to be tracked as part of the task.
Right now the monitor is statically coded to always show (in the table output) 16 character width for the name, and a column for the core id. However, the task name could be shorter or longer (16 is the default configured freertos max task name length), and the core id support may not be compiled in (by default it is not).
This PR updates the table printing to not show core id column if it's not supported, and to update the name column width based on the configured max task name length.
Building and running the `monitor/example` on a QtPy ESP32s3.
Standard …

feat(monitor): update monitor to support longer task name printing

---

components/hid-rp/include/hid-rp-gamepad.hpp

* Update hid-rp-gamepad to use `unit::degree()` instead of hard-coded constant for better readability
Makes the code easier to understand and provides a better example for using hid-rp library rather than hard-coding the 0x0014 constant (0th nibble = system, 4 = english rotation; 1st nibble = length exponent, 1 = degrees).
Building and running the `hid_service/example` on a QtPy ESP32s3 and testing with iOS and Android.

feat(hid-rp): update gamepad to use `unit::degree()` for hat switch

---

.github/workflows/static_analysis.yml

Remove duplicate (deprecated) run of static analysis.
With the last #216 the static analysis action works for PRs from forks (analyzes the code and posts an issue/pr comment), but has a duplicate run which fails. This removes that duplicate run.
If this PR has working static analysis, everything is good.

ci: fix static analysis for forks to remove redundant failing execution

---

components/hid-rp/example/main/hid_rp_example.cpp
components/hid-rp/include/hid-rp-gamepad.hpp
components/hid_service/example/main/hid_service_example.cpp

* Update `hid-rp/include/hid-rp-gamepad.hpp` (`espp::GamepadInputReport`) to support specifying the data type for the joystick and trigger inputs (default is `std::uint16_t`).
Previously the storage type was implicitly `uint16_t` and the `min/max` values were also `uint16_t`, but sometimes (and for some platforms) you may want to support negative ranges or you may want to only use one byte for joystick or triggers. This PR updates the class so you can specify such implementations.
Building and running the `hid-rp/example` and the `hid_service/example` on a QtPy ESP32s3. Tested the `hid_service/example` with Android and iOS.

feat(hid-rp): update gamepad to support joystick/trigger storage type specification

---

components/nvs/example/README.md
components/nvs/example/main/nvs_example.cpp
components/nvs/include/nvs.hpp

* Fix hard-coded ns/key in bool overloads
* Add additional functions to take string_views
* Add error codes and update logging
* Update example to test more cases
* Update readme
The bool overloads for the nvs functions had a copy/paste hard-coded namespace and key value. This fixes that issue. It also adds additional overloads for accepting std::string_view and updates the error codes to be NVS specific.
Building and running `nvs/example` on a QtPy ESP32S3.

fix(nvs): fix hard-coded ns/key in bool overloads

---

components/timer/example/main/timer_example.cpp
components/timer/include/high_resolution_timer.hpp

* Add `skip_unhandled_events` to `HighResolutionTimer::Config` to allow caller to configure (default `false`).
* Add `dispatch_method` to `HighResolutionTimer::Config` to allow caller to configure (default `ESP_TIMER_TASK`).
Allows more granular configuration / customization using the full esp_timer API.
Building and running the `timer/example` on a QtPy ESP32S3.
With `CONFIG_ESP_TIMER_PROFILING` enabled:
With it disabled:

feat(timer): allow `skip_unhandled_events` and timer dispatch configuration for `HighResolutionTimer`

---

components/kts1622/include/kts1622.hpp

Add a new set_direction() method to change the I/O direction register to the KTS1622 class.
The EN_USB_PLG is controlled by the right KTS1622 I/O expander P1_4 on the proto1 sample.
During the UM3506 FW update, this pin outputs the same value as the EN_USB_PLG_UM pin to prevent the UM3506 bootloader from losing control and causing USB MUX malfunctions (USB REC/PLUG miss-switching).
The I/O direction register needs to be changed at the EN_USB_PLG_UM port level read and at the EN_USB_PLG port output.
This new set_direction() method is used in the following function:
[[FIR-137] Ability to update UM3506 FW from ESP32](https://github.com/Backbone-Labs/niji/issues/199#top)
#199
I confirmed that the following um3506_example.cpp code reads the value of the EN_USB_PLG_UM port and outputs it from …

feat(kts1622) Add new set_direction method to change I/O direction register

---

.github/workflows/build_and_publish_docs.yml
doc/Doxyfile
doc/requirements.txt

* Update esp-docs to 1.10.0
* Update workflow to build docs into pdf and upload the pdf
* Update workflow to allow `workflow_dispatch` which enables the build and publish docs workflow to be manually run on a specific branch / commit / PR for testing.
* Keeps doc deps up to date
* Provides pdf of docs
This PR.

doc: update deps and build pdf

---

components/nvs/example/main/nvs_example.cpp
components/nvs/include/nvs.hpp

* Add template specialization functions for reading/writing string values to NVS
* Update example to test new functions
Strings are useful basic elements to store in NVS. The underlying storage supports them, but the `espp::Nvs` class did not, since they require slightly different APIs. This PR updates the implementation to support string storage using those APIs.
Building and running the `nvs/example` on a QtPy ESP32s3.

feat(nvs): update to support string values

---

components/nvs/include/nvs.hpp

Fixed a bug by changing the ec parameter of erase() to pass the error code by reference, allowing it to correctly update the error state within the method.
Prior to this, changes made to the error code by erase() won't affect the original error code outside the method. This fix corrects the signature to reflect the ec convention of the other methods in the Nvs class.

fix(nvs): pass ec reference to erase()

---

components/adc/include/adc_types.hpp

Use <hal/adc_types.h> instead of older <driver/adc.h> which is deprecated (and unused elsewhere within espp).
Removes spurious warning.
Building adc example.

fix(adc): fix deprecation warning from include in adc_types.hpp

---

components/ble_gatt_server/example/main/ble_gatt_server_example.cpp
components/ble_gatt_server/include/ble_gatt_server.hpp
components/ble_gatt_server/include/ble_gatt_server_callbacks.hpp
components/ble_gatt_server/src/ble_gatt_server_callbacks.cpp
components/gfps_service/example/main/gfps_service_example.cpp
components/gfps_service/src/nearby_ble.cpp
components/hid_service/example/main/hid_service_example.cpp

* Update `espp::BleGattServer` for breaking API changes to esp-nimble-cpp which add support for passkey injection
* Update `espp::GfpsService` to use new esp-nimble-cpp APIs to perform passkey injection as part of the GFPS pairing / security process
Previously we had a working GFPS implementation, but had a `TODO` related to support for passkey injections, which are required for a proper GFPS implementation, however esp-nimble-cpp did not support that feature.
After [esp-nimble-cpp#165](https://github.com/h2zero/esp-nimble-cpp/pull/165), it is now supported.
This PR updates the ble gatt server and gfps service accordingly.
https://github.com/h2zero/esp-nimble-cpp/pull/165
Building and running the `hid_service/example` and the `gfps_service/example` (as well as an actual gpfs service).

feature(BLE): Update NimBLE, BleGattServer, and GfpsService to support Passkey Injection

---

components/bldc_haptics/include/detent_config.hpp
components/bldc_motor/include/foc_utils.hpp

I marked 3 BLDC related functions as `inline`
With these 3 functions not marked as inline, I would get `Multiple definition of` linking errors.
By building [this](https://github.com/smartknob-ha/firmware/tree/feature/motor) project.

fix: Marked some functions as inline

---

components/file_system/example/main/file_system_example.cpp
components/file_system/include/file_system.hpp
components/file_system/src/file_system.cpp

Move various `const` APIs in `espp::FileSystem` to be `static` instead, so they can be used without initializing the filesystem.
There are use cases where you may want to get the mount point or access some of the APIs of the file system which do not require it to have been initialized without initializing the file system. This PR updates some const APIs to be static allowing such use.
Building and running the `file_system/example` on QtPy ESP32s3.

feat(file_system): update so that mount point and related const APIs are static

---

components/logger/include/logger.hpp

* Add `logger/Kconfig` configuration allowing configuration of ESPP Logger `max log level`, which defaults to `4` (all logs compiled in)
* Update `espp::Logger` to compile out the implementations of the various log functions depending on whether the config has enabled them. 
As a system moves to production (or reaches the end of its partition size 😅), it may be necessary to optimize out log levels that are not being used so they do not contribute to code size.
Building and running `logger/example` on a QtPy ESP32s3 and compiling it with log level 4 (ALL) enabled, as well as compiling and running it with log level 2 (only errors and warnings). Checked that the compiled out logs did not print and that the resultant binary was smaller.
New Menuconfig:
Execution with only `warn` and `error` …

feat(logger): allow compiling out `espp::Logger` levels / verbosity to reduce size

---

components/esp-box/example/main/esp_box_example.cpp
components/esp-box/include/esp-box.hpp
components/esp-box/src/esp-box.cpp

Add warning to code and docs recommending that `EspBox::initialize_touch()` be called after `EspBox::initialize_display()`.
While there are plenty of cases where users will not want to use LVGL or will want to use the touchpad for other reasons or with other systems, it's a good idea to instruct people that they will need to call `initialize_touch()` after `initialize_display()` if they want LVGL to properly recognize their touch input. Otherwise it will silently fail and LVGL will not retrieve the touch data, so no touch input will be handled by lvgl.

feat(esp-box): warn users if they try to initialize touch before display

---

components/input_drivers/include/encoder_input.hpp
components/input_drivers/include/keypad_input.hpp
components/input_drivers/include/touchpad_input.hpp

Add error logs to input_drivers if lvgl registration fails.
Related to #273 and https://github.com/esp-cpp/esp-box-emu/pull/74, the input registration would silently fail. This improves it by making it less silent :)

feat(input_drivers): Add error logs when lvgl registration fails

---

.gitmodules

Switch from ssh to https for submodules
Closes #281 
In short, allows people who have not set up ssh / are using github to clone / fork / use this as a submodule.
Clone, checkout this branch, submodule update

fix #281 switch from ssh to https submodules

---

components/esp-box/include/esp-box.hpp
components/esp-box/src/esp-box.cpp

* Update `esp-box` to update touchpad interrupt configuration depending on which box is detected.
The `esp-box` had been updated to use the touchpad interrupt for reading the touchpad, but unfortunately the ESP32-S3-BOX didn't use the same touchpad interrupt configuration as the ESP32-S3-BOX. 
This code updates the component to configure the touchpad interrupt to the correct configuration depending on the detected hardware.
Building and running the `esp-box/example` on both BOX-S3-ESP32 and BOX-S3-ESP32-3

fix(esp-box): Ensure touch interrupt is configured properly for ESP-BOX and ESP-BOX-3

---

components/color/example/main/color_example.cpp
components/color/include/color.hpp
components/color/src/color.cpp

* Update `espp::Rgb` to have `uint32_t` constructor for providing hex RGB color values such as `0xFF0000` (red)
* Update `espp::Rgb` to support float (default), decimal, and hex format specifiers
* Update `espp::Rgb` to have `uint32_t hex() const;` method 
* Some people prefer to specify colors using uint32_t hex codes rather than float RGB values.
* We should also support such preferences when printing the data so that they do not have to do the conversion each time they want to print the colors.
Building and running `color/example` on QtPy ESP32S3.
New part of the test which tests the format specifiers, the `.hex()` function, and the `uint32_t` constructor.

feat(color): add Rgb(uint32_t hex) constructor and `f`loat, `d`ecimal, and he`x` format specifiers

---

components/task/include/task.hpp

Check the started_ flag before trying to stop/join the thread.
Redundant calls to task stop seem to be prone to exceptions down in std::thread::join. This doesn't quite make sense because of the joinable call ahead of time

Only do thread join when we know thread is running

---

.github/workflows/build.yml

Update build.yml to only build component examples for changes to components or externals.
Changes to library or docs shouldn't build examples, that's a waste of time / resources.

chore(ci): Only run component builds for changes to components or externals

---

components/task/example/main/task_example.cpp
components/task/src/task.cpp

* Update task example to demonstrate multiple (10) threads competing to stop a single task
This kind of stress-test example helps test the robustness of the implementation and helps to test for race conditions, deadlocks, etc.
Building and running `task/example` on a QtPy ESP32-S3.
In the screenshot, you can see that 10 tasks are spawned, but only 4 of them pass the `started_` check within `Task::stop()`, showing that multiple threads compete to join the task thread without issue.

example(task): Add example showing many threads competing to stop a single task

---

components/task/example/main/task_example.cpp
components/task/include/task.hpp
components/task/src/task.cpp

* Update task/example to better demonstrate contention between multiple threads trying to stop a single task - by adding an additional non-preemptible wait between the cv.wait and returning from the task function.
* Update `espp::Task` to have a mutex protecting the `thread_` member and refactor code to ensure the thread_ is always protected and the thread is always notified and joined where appropriate.
Before this change, the updated example caused an abort (see screenshot below) due to multiple threads trying to call join since the thread_ was not protected and they all saw the thread was joinable.
After this change, only a single thread is able to stop the task, while the others either see that it has already been stopped (same as previous behavior) or they now block on the …

fix(task): Protect access of thread_ to ensure multiple threads cannot call join()

---

components/display_drivers/include/st7789.hpp

Ensure bit 3 (RGB vs BGR) in madctl is always set properly, and is not overridden by rotation updates.
It was found in various projects such as esp-box-emu that the color order was incorrect, and the culprit was tracked down to the new function which was overriding the color order bit setting in madctl.
Building and running within the [camera-display](https://github.com/esp-cpp/camera-display) and the [esp-box-emu](https://github.com/esp-cpp/esp-box-emu) projects, and as part of https://github.com/esp-cpp/camera-display/pull/8

fix(display_drivers): Ensure st7789 madctl RGB order bit is always set properly

---

components/rtsp/src/rtsp_client.cpp

Fix `response_data.starts_with("RTSP/1.0")` check in `RtspClient::parse_response` which had a logic inversion.
This check is required for the rtsp client to properly communicate with the server.
Building and running within the [camera-display](https://github.com/esp-cpp/camera-display) project, as part of https://github.com/esp-cpp/camera-display/pull/8

fix(rtsp): Fix logic error in rtsp client response parsing

---

components/display/include/display.hpp
components/display_drivers/include/display_drivers.hpp
components/display_drivers/include/gc9a01.hpp
components/display_drivers/include/ili9341.hpp
components/display_drivers/include/st7789.hpp
components/display_drivers/src/gc9a01.cpp
components/display_drivers/src/ili9341.cpp
components/display_drivers/src/st7789.cpp
components/esp-box/example/main/esp_box_example.cpp
components/esp-box/include/esp-box.hpp
components/esp-box/src/esp-box.cpp
components/input_drivers/include/touchpad_input.hpp
components/interrupt/include/interrupt.hpp
components/matouch-rotary-display/example/main/matouch_rotary_display_example.cpp
components/matouch-rotary-display/include/matouch-rotary-display.hpp
components/matouch-rotary-display/src/matouch-rotary-display.cpp
components/t-deck/example/main/t_deck_example.cpp
components/t-deck/include/t-deck.hpp
components/t-deck/src/t-deck.cpp
components/t-dongle-s3/example/CMakeLists.txt
components/t-dongle-s3/example/main/t_dongle_s3_example.cpp
components/t-dongle-s3/include/t-dongle-s3.hpp
components/t-dongle-s3/src/t-dongle-s3.cpp
components/wrover-kit/example/CMakeLists.txt
components/wrover-kit/example/main/wrover_kit_example.cpp
components/wrover-kit/include/wrover-kit.hpp
components/wrover-kit/src/wrover-kit.cpp

* Add `mirror_x` and `mirror_y` variables to the display drivers which are copied from the config.
* Update the display drivers' `rotate()` functions to additionally account for the `mirror_x` and `mirror_y` settings, similar to how they were accounting for the `swap_xy` setting.
* Update the display drivers' `rotate()` functions to flip the bits instead of or-ing them
* Update the display drivers to properly handle x/y offset updates when rotating the screen
* Update the HAL for various display boards to allow more complete configuration of the display task and refresh period
It was found that the latest changes from #265 which added the rotate function caused lvgl to not properly match the touch location with the screen location (found in https://github.com/esp-cpp/esp-box-emu/pull/87). …

fix(display_drivers): Handle rotation properly, accounting for mirror x/y, mirror portrait, and updated offsets

---

components/logger/Kconfig
components/logger/example/main/logger_example.cpp
components/logger/include/logger.hpp

* Move `get_time()` to be public so others can use it.
* Add some cursor commands for sending ANSI terminal escape sequences
Allows for more complex logging behavior to be developed as well as some simple terminal applications.
Support for the cursor commands (which are static functions) can be compiled in either by setting `ESPP_LOGGER_CURSOR_COMMANDS_ENABLED=1` as a compile definition, or by using menuconfig. For ESP-based systems which use menuconfig, the cursor commands are enabled by default.
Building and running the `logger/example` on a QtPy ESP32s3.

feat(logger): Add support for cursor commands and expose `Logger::get_time()` as public

---

components/task/example/main/task_example.cpp
components/task/include/task.hpp
components/task/src/task.cpp

* Add `static bool Task::configure_task_watchdog(timeout_ms, panic_on_timeout)` to initialize / reconfigure the watchdog timer subsystem.
* Add `bool Task::start_watchdog()` and `bool Task::stop_watchdog()` to (de-)register the task with the watchdog timer and inform the task to start resetting the watchdog timer.
* Add `static std::string Task::get_watchdog_info(error_code)`, which can be used (with some caveats mentioned in the docstrings) to get info about tasks which triggered the watchdog.
* Add examples for configuring the watchdog to the task example
* Update task example to use logger for easier to read / clearer delineation between the tests.
During debugging, it can be very useful to track execution of various tasks and ensure they do not deadlock or block for too long. This …

feat(task): Add support for enabling task watchdog on an `espp::Task`

---

components/led/CMakeLists.txt
components/led/include/led.hpp

* Allow LEDC interrupt service (ISR) to be installed on specific cores
Similar to the I2C, we'd like to be able to specify which core the interrupt is installed on (since there are only a limited number of slots available on each core).
* Building and running the `led/example`

feat(led): allow LEDC ISR to be configured onto specific cores

---

components/task/src/task.cpp
components/timer/example/main/timer_example.cpp
components/timer/src/high_resolution_timer.cpp

* Remove check on `is_started()` in `start_watchdog()` for `Task`, `Timer,` and `HighResolutionTimer`
* Allows users to call `start_watchdog` before calling `start`
* Allows use of `start_watchdog` with `oneshot` `HighResolutionTimers`
Building and running `task/example` and `timer/example` on QtPy ESP32s3.

feat(task/timer): allow watchdog to start even if task/timer has not

---

components/task/example/main/task_example.cpp
components/task/include/run_on_core.hpp
components/task/include/task.hpp

* Add method for running a function on specific core without blocking the thread. Resources for the thread will be automatically cleaned up.
Similar to `espp::task::run_on_core`, we'd like to be able to run functions on specific cores without creating and managing a `espp::Task`, so that once the function completes, the thread resources will be automatically cleaned up, and we'd like to be able to start the work without blocking the calling thread context.
Building and running `task/example` on a QtPy ESP32s3.

feat(task): Add `espp::task::run_on_core_non_blocking` static method

---

components/task/example/main/task_example.cpp
components/task/include/run_on_core.hpp

* Add `run_on_core*` API overloads which take `espp::Task::BaseConfig`
* Add `const std::string &name` default arguments to `run_on_core*` APIs
Allows more flexible configuration of the run-on-core threads and reuse of task config structures for more consistency.
Building and running `task/example` on a QtPy ESP32s3.

feat(task): Allow `Task::BaseConfig` to configure `run_on_core` and `run_on_core_non_blocking`

---

components/gfps_service/src/nearby_ble.cpp
components/rtsp/include/rtcp_packet.hpp

* Remove address change implementation from gfps_service, since it is not needed and may constrain application flexibility / design
* Update `nearby_platform_GetBleAddress()` to return the random address directly from NimBLE, for applications which support random addresses
In development of an application which utilizes address randomization, it was found that the current GFPS implementation failed. This update allows random addresses to work with GFPS.
Using address randomization code such as:
```c++
ble_addr_t addr;
int rc = 0;
// generate a random address
rc = ble_hs_id_gen_rnd(0, &addr);
if (rc != 0) {
logger_.error("Failed to generate random address");
return false;
}
// make sure we set our address type
NimBLEDevice::setOwnAddrType(BLE_OWN_ADDR_RANDOM, false);
// set the address
rc …
```

feat(gfps_service): Update GFPS to support use of random addreses

---

components/ble_gatt_server/include/ble_gatt_server_callbacks.hpp
components/ble_gatt_server/include/device_info_service.hpp
components/ble_gatt_server/src/ble_gatt_server_callbacks.cpp
components/hid_service/example/main/hid_service_example.cpp
components/hid_service/include/hid_service.hpp

* Update to latest esp-nimble-cpp submodule
* Update ble gatt server callback implementation to remove const from parameters matching updated APIs
* Update to use setValue methods which accept std::string and std::string_view (since they have .data() and .size())
* Keeps submodules up to date
* Adds new methods / interfaces enabling cleaner and safer code
* Building and running `hid_service/example` on a QtPy ESP32-S3 and ensuring it works properly
* Building and running a project with GFPS configured and ensuring it works properly.

chore: Update esp-nimble-cpp submodule to latest

---

components/ble_gatt_server/include/device_info_service.hpp

Change to have BLE SIG be the default for the PnpId struct.
Given that the `DeviceInfoService` is used over BLE, this sets the default to be more reasonable for BLE devices.

fix(device_info_service): Update default value for vendor id source to be 0x01 (BLE SIG) since its predominantly used for ble

---

components/file_system/include/file_system.hpp
components/file_system/src/file_system.cpp
pc/tests/file_system.cpp

* add `espp::FileSystem::file_entry_string(std::filesystem::path &path, const ListConfig &config, const std::string &prefix="")` method for external use
* refactor `espp::FileSystem::list_directory(...)` to use `espp::FileSystem::file_entry_string(...)` function
* Add file system PC test to ensure host-side / non ESP_PLATFORM code paths work just as well
* Enables wider use-cases for the file system API
* Allows simpler testing of file system changes on a host PC using the library
* Building and running the `file_system/example` on a QtPy ESP32S3
* Building the x-plat library, building the new `pc/tests/file_system.cpp` test and running it on MacOS

feat(file_system): Allow single entry to string function

---

components/adc/include/continuous_adc.hpp
components/adc/include/oneshot_adc.hpp

* Add mutex to `OneshotAdc` APIs
* Remove warning in continuous ADC
Ensures that the oneshot adc can safely be used from multiple threads
Building and running `adc/example` on a QtPy ESP32s3.

feat(adc): Add mutex ensuring `OneshotAdc` can be used safely from multiple threads

---

lib/CMakeLists.txt
lib/espp.cmake

* Break out `hid-rp` and `magic_enum` externals into their own separate cmake variable, to handle them separately from everything else when installing (since they're a little non-standard)
* Add and use `ESPP_INCLUDE_DIRS` cmake variable for setting the include dirs
* Add reusable cmake functions `espp_install_includes(folder)` and `espp_install_python_module(folder)`
Cleans up the output `lib/pc` folder so that all includes are now properly within `lib/pc/include`, without having some duplicates within `lib/pc` alongside the libraries.
* `lib/build.sh` to do a clean build of the library (after removing lib/build and lib/pc)
* `pc/build.sh` to build the pc tests using the library, ensuring they still build and run
* Ran the python tests within the `python` folder:
* `$ python3 task.py`
* …

feat(lib): Update how includes are installed and handle non-standard externals better

---

components/event_manager/include/event_manager.hpp
components/event_manager/src/event_manager.cpp
components/task/include/run_on_core.hpp

* Added `notified` flag to `SubscriberData` which is set / cleared appropriately and used as predicate to `cv.wait(...)`
* Added `notified` bool used in `run_on_core` to ensure the `cv.wait(...)` uses it as the predicate, ensuring the blocking run on core does not return early
Spurious wakeups can happen (see [c++ docs on condition variable wait and associated methods](https://en.cppreference.com/w/cpp/thread/condition_variable/wait)). On ESP this can happen for instance if you enable light sleep and have some time-dependent wakeups.
Even though the methods changed in this PR use `wait(...)` instead of `wait_for(...)` or `wait_until(...)`, these changes were applied to ensure better adherence to programming guidelines and recommendations from the c++ reference / standard.
* Building and …

fix: Update `EventManager` and `task::run_on_core` to ignore spurious wakeups if they happen

---

components/nvs/example/main/nvs_example.cpp
components/nvs/include/nvs.hpp
components/nvs/include/nvs_errc.hpp
components/nvs/include/nvs_handle_espp.hpp

* Update `espp::NvsHandle` to support `erase(std::error_code&)` and `erase(std::string_view key, std::error_code&)` methods
* Update `espp::Nvs` to support `erase(namespace, key)`, and `erase(namespace)` methods
* Update example to test new methods
Erase methods were missing, but can be quite useful for specific keys or namespaces, without having to fully erase the flash.
This PR addresses that oversight.
Building and running `nvs/example` on a QtPy ESP32s3 and ensuring it works as intended.
After full erase:

feat(nvs): Add erase key and erase namespace methods

---

components/interrupt/example/main/interrupt_example.cpp
components/interrupt/include/interrupt.hpp

* Update `Interupt` to track the minimum number of free spaces in the queue and an API for querying it, over the lifetime of the object
In complex systems with many tasks and many interrupts, there is a chance that the configured interrupt queue size (default=10) is too small and may fill up, causing some interrupts to be missed. 
This may also help to indicate if there is additional filtering required on the interrupt line (either using the `espp::Interrupt::FilterType` config or by implementing hardware filtering).
This may also occur if the interrupt handler task priority is too low and there are many other tasks in the system starving the interrupt task of CPU time.
Building and running the `interrupt/example` on a QtPy ESP32s3.

feat(interrupt): Add API for tracking and getting the min queue size

---

components/interrupt/include/interrupt.hpp

* Add `enable` / `disable` APIs for specific interrutps
* Add `remove` APIs for specific interrupts
* Add `remove_all`
* Add `disable_all`
* Refactor how interrupts are configured somewhat to ensure they are not enabled until after the handler has been registered
* Update interrupt PinConfig to have `auto_reenable` flag (default=true) to mirror previous behavior, but to allow the interrupt to not re-trigger until explicitly re-enabled by the caller.
* Add more info about interrupt configuration to class doc
More complex use of the interrupts class necessitated being able to manually enable/disable interrupts via caller code. This update also enables better use of level interrupts in addition to edge interrupts.
* Building and running `interrupt/example` on QtPy ESP32s3.
* Building within …

feat(interrupt): Improve Interrupt implementation and API

---

components/ble_gatt_server/include/ble_gatt_server_menu.hpp

Update esp-nimble-cpp to v2.0
Keeps our submodule up to date :)
* Building and running the `hid_service/example` on QtPy ESP32s3

chore: Update esp-nimble-cpp to latest v2.0

---

components/task/include/run_on_core.hpp
components/task/src/task.cpp

* Ensure the detached task function calls `vTaskDelete(nullptr)` instead of returning. It is not needed in the `Task` itself because we do a `join` on that thread instead of detaching
Ensures that we follow the spec for what you must do when exiting the return function in FreeRTOS tasks under all conditions.
Building and running `task/example` on QtPy ESP32s3.

fix(task): call `vTaskDelete` at end of `std::thread` in `task::run_on_core_non_blocking`

---

components/task/include/run_on_core.hpp

* Update `espp::task::run_on_core` (blocking) APIs to have a `bool ensure_task = false` parameter which (if true) will ensure that the function is run in a separate task, regardless of the requested core and current core id.
* Update `espp::task::run_on_core` (blocking) APIs so that `core_id = -1` (do not care) parameter will still spawn a separate task, instead of running in the same context as the calling function.
The `espp::task::run_on_core` provides a convenient API for ensuring a function is run in a separate task (with its own stack) in a way that cleans up the memory and provides easy to read code. However, it was not great for guaranteeing that the requested stack is provided to the function, since there were conditions when it would run in the calling context (which may not …

feat(task): Allow `run_on_core` callers to ensure a separate task is created

---

components/hid-rp/example/main/hid_rp_example.cpp
components/hid-rp/include/hid-rp-gamepad.hpp
components/hid_service/example/main/hid_service_example.cpp

* Add `espp::XboxBatteryInputReport` to `hid-rp-gamepad.hpp`
* Update `hid-rp/example` to check compilation
* Update `hid_service/example` to actually use and test the battery report
Some systems (such as iOS) show battery status as part of their gamepad display - and this status is different from the `BatteryService`. To be able to have some control over this, we need to implement this report type.
This is especially important when masquerading as an Xbox controller.
Building and running `hid_service/example` on QtPy ESP32s3 and checking on iPhone to make sure the `GameControllers` screen in `Settings>General` shows the updating battery level there.
Note: battery service still shows correct info in the batteries widget:

feat(hid): Add xbox battery input report

---

components/codec/es8311/es8311.hpp

Add a missing include to `es8311.hpp`
For some reason, only after upgrading to v6.10.0 of platform-espressif32 did we start getting compiler errors on this.
First failing pipeline after upgrade:
- https://github.com/smartknob-ha/firmware/actions/runs/13017702817/job/36313111332?pr=70#step:5:331
Pipeline where I've added the `#include <cstdint>`:
- https://github.com/smartknob-ha/firmware/actions/runs/13038847244/job/36375735030

fix(build): Fix missing include since platform-espressif32 v6.10.0

---

.github/workflows/build.yml
.github/workflows/static_analysis.yml
README.md
components/file_system/example/main/file_system_example.cpp

* Update build and static analysis to target esp-idf 5.4
* Update file system example to only warn for ESP-IDF targets < 5.4
* Update README
Keeps us up to date with latest stable releases
* Building and running `file_system` example with ESP-IDF 5.4 on QtPy ESP32S3
* CI

chore: Update CI to use ESP-IDF 5.4

---

components/ble_gatt_server/example/main/ble_gatt_server_example.cpp
components/ble_gatt_server/include/battery_service.hpp
components/ble_gatt_server/include/ble_gatt_server.hpp
components/ble_gatt_server/include/device_info_service.hpp
components/ble_gatt_server/src/ble_gatt_server_callbacks.cpp
components/hid_service/example/main/hid_service_example.cpp

* Add some new methods to `BleGattServer`
* Remove logging from many methods which was unnecessary, and mark those methods `const`
* Update `hid_service` example to print Manufacturer name, model number, and PnpId for remote device
* Update `hid_service` example to print connected info more clearly and have cleaner code
* Update `hid_service` example to wait until after auth to read values from the remote
* Update `DeviceInfoService` to have static methods for parsing received PnpId
* Update `DeviceInfoService` and `BatteryService` so UUIDs are public
* Update `esp-nimble-cpp` submodule to latest, brining in improvements as well as new feature to register store callback for managing bonding info when it fills up.
* Allows you to read more information from the remotely connected device, if …

feat(ble): Update `BleGattServer` and `esp-nimble-cpp` submodule

---

components/cli/CMakeLists.txt
components/cli/include/cli.hpp

* Update usb/uart vfs drivers to use latest, fixing deprecation warning
Keeps the code up to date, using latest and removes all warnings from builds.
Build and run `ble_gatt_server/example` (which uses CLI) on QtPy ESP32s3.

fix(cli): Fix deprecation warning

---

components/hid_service/example/main/hid_service_example.cpp
components/hid_service/example/sdkconfig.defaults

* Implement device callback for handling bond storage overflow
* Print bonded devices when booting up
* Print bonded devices when a device connects
* Update defaults to support 5 devices bonded at a time
Helps showcase multiple device support with storage management callback
Build and run `hid_service/example on QtPy ESP32S3 and ensure it can bond to the number of bonded devices configured
NOTE: the tests were run with max bonds / cccds set for 10 devices, but the code was changed for 5 devices.

feat(hid_service): Allow example to support multiple bonded devices

---

components/hid_service/include/hid_service.hpp

feat(hid_service): Expose UUIDS for use by others

---

components/bldc_haptics/include/bldc_haptics.hpp

Add a function set_position for use with the bldc_haptics class so we can change the current "haptic position" to any valid position within the current DetentConfig.
Say you have a pre-existing value that you would like to change using, for example, the `COARSE_VALUES_STRONG_DETENTS` config, and the currently stored value is 28.
With the current logic the `current_position_` will always be set on the position of the motor shaft, which might not be equal to our desired starting point of 28.
Calling this function when initializing a config so that it always starts "midway" in the DETENT config, regardless of the position I turn the shaft to before rebooting. (https://github.com/smartknob-ha/firmware/blob/ef9ff84e42428ef23f151100f5b5302cec8a44cd/src/main.cpp#L82)
Tested on a Smartknob-HA

feat(bldc_haptics): add set_position function

---

components/hid-rp/CMakeLists.txt
components/hid-rp/include/hid-rp-gamepad-formatters.hpp
components/hid-rp/include/hid-rp-gamepad.hpp

* Add formatter for easy printing of gamepad data
* Add `set_data` function for setting the raw bytes of the report (e.g. from a received binary input report) for parsing it
Helps when you want to parse an input gamepad report of this type and print the values
* Build and run within `esp-usb-ble-hid` project and ensure that the parsed report is correct and prints properly

feat(hid-rp): Add gamepad `set_data` and formatters

---

components/display/include/display.hpp
components/display_drivers/example/main/display_drivers_example.cpp
components/esp-box/example/main/esp_box_example.cpp
components/esp-box/src/video.cpp
components/matouch-rotary-display/example/main/matouch_rotary_display_example.cpp
components/matouch-rotary-display/src/matouch-rotary-display.cpp
components/seeed-studio-round-display/example/main/seeed_studio_round_display_example.cpp
components/seeed-studio-round-display/src/seeed-studio-round-display.cpp
components/t-deck/example/main/t_deck_example.cpp
components/t-deck/src/t-deck.cpp
components/t-dongle-s3/example/main/t_dongle_s3_example.cpp
components/t-dongle-s3/include/t-dongle-s3.hpp
components/t-dongle-s3/src/t-dongle-s3.cpp
components/wrover-kit/example/main/wrover_kit_example.cpp
components/wrover-kit/src/wrover-kit.cpp

* Update LVGL submodule to 9.2.2
* Update display to use public APIs instead of private APIs
* Update affected examples to use public APIs instead of private APIs
* Update t-dongle to have proper color and display offset configuration
* Keeps our LVGL up to date with the latest fixes, features, and performance improvements
* Ensures the `t-dongle-s3` component works across a wide variety of use cases
* Building and running `t-dongle-s3/example` on a T-Dongle S3.

feat(lvgl): Update to LVGL v9.2.2

---

components/hid-rp/include/hid-rp-gamepad.hpp
components/hid-rp/include/hid-rp-switch-pro-formatters.hpp
components/hid-rp/include/hid-rp-switch-pro.hpp
components/hid-rp/include/hid-rp-xbox.hpp

* Add some concepts for structs to make it easier to get / set buttons with custom / user-defined structs/classes without having to subclass
* Add more getters / setters for each Switch and Xbox
* Add specializations to the Xbox class to explicitly match buttons for the xbox controller
Makes using the controllers (and converting between controller report types) easier / more painless
Build and run `hid-rp/example`
Build and run within [esp-usb-ble-hid](https://github.com/finger563/esp-usb-ble-hid)

feat(hid-rp): Flesh out gamepads to fill out their interfaces

---

components/hid-rp/include/hid-rp-switch-pro.hpp

* Add structures for subcommands, imu data, and refactor how some of the getters/setters work
Makes the code easier to read and provides more complex use.
Build and run as part of https://github.com/finger563/esp-usb-ble-hid project

feat(hid-rp): Flesh out switch pro report more

---

components/hid-rp/include/hid-rp-switch-pro.hpp

* Fix issue with switch pro hid report `reset()` resetting the counter value, which prevented `increment_counter()` from working
* Update switch pro to clear all the report bytes to 0 ensuring subcommand / reply data is zeroed out
* remove additional sets in the reset command so app can do it as necessary
Fixes an issue specifically with switch compatibility (ios/android didn't seem to care) if you wanted to simplify application code by calling `increment_counter`. This does not affect code that is already using `set_counter` after calling `reset()` of course.
* Building and running https://github.com:/finger563/esp-usb-ble-hid with this code and doing longer play session with the switch

fix(hid-rp): Fix switch pro resetting counter

---

components/task/include/run_on_core.hpp

* Remove call to `vTaskDelete(nullptr)` from the end of the thread function
`vTaskDelete(nullptr)` was added as part of #353 based on spec. It was erroneously causing the detached thread to leak memory for each call to `run_on_core_nonblocking`. Using esp heap tracing I was able to determine that it did leak memory, while the updated code does not leak memory. Additionally, I used the `TaskMonitor` to ensure that the tasks are properly destroyed and are no longer registered within the system.
Note: as mentioned in the [esp-docs](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/system/heap_debug.html#false-positive-memory-leaks), there will be some leaks reported which are benign. What is important is that as we vary the number of times that …

fix(task): Fix memory leak from `task::run_on_core_nonblocking`

---

components/ble_gatt_server/include/ble_gatt_server.hpp
components/ble_gatt_server/include/generic_access_service.hpp
doc/Doxyfile
doc/en/ble/generic_access_service.rst
doc/en/ble/index.rst

* Add `espp::GenericAccessService`
* Add method in `BleGattServer` to read remote `Appearance` of client
* Update docs
Adds functionality for reading remote client info and adds some information about the BLE GAS - though its not needed for implementation.
* Build `ble_gatt_server/example`

feat(ble_gatt_server): Add (unneccessary) definitions for GenericAccessService

---

components/display/include/display.hpp

* Update `espp::Display` to store the `flush` and `rotate` functions and to pass `this` as the context for the lvgl `display` and `event` callback
This allows any arbitrary function (including bound class member functions) to be passed for the flush callback and rotate callbacks, instead of requiring that they match the signatures and linkage of the lvgl lower-layer functions. This will enable a follow-up PR which allows the display drivers to no longer be static classes, further enabling multiple displays to be used in a single project.
Build and run `esp-box/example`, `t-dongle-s3/example` to ensure the existing code still works.

feat(display): Update to support multiple displays

---

components/esp-box/src/video.cpp
components/matouch-rotary-display/src/matouch-rotary-display.cpp
components/seeed-studio-round-display/src/seeed-studio-round-display.cpp
components/t-deck/src/t-deck.cpp
components/t-dongle-s3/src/t-dongle-s3.cpp
components/wrover-kit/src/wrover-kit.cpp

* Add missing `if (!parameters.empty())` check when sending second spi transaction to `EspBox`
Ensures the spi transactions do not fail.
Build and run example and other code on esp-box.

fix(esp-box): Add missing check for empty parameters in spi transmit

---

components/esp-box/include/esp-box.hpp
components/esp-box/src/audio.cpp
components/esp-box/src/buttons.cpp
components/qtpy/src/qtpy.cpp

* Update esp-box to have optional registration of interrupt callbacks for mute and boot buttons
* Update esp-box to check sound initialized before dealing with sound functions
* Update qtpy to only register button interrupt if not already registered
Fleshes out more of the hardware functionality in esp-box; ensures the API cannot be misued and handles cases where mute button is initialized but sound is not.
Building esp-box and qtpy examples.

feat(esp-box): Add interrupts for mute and boot buttons

---

components/runqueue/CMakeLists.txt
components/runqueue/example/README.md
components/runqueue/example/main/runqueue_example.cpp
components/runqueue/include/runqueue.hpp
components/runqueue/src/runqueue.cpp

* Update runqueue to generate and store an ID associated with each function, returning the id when functions are added to the queue
* Allow querying of the ids currently in the queue or running
* Allow removal of functions by id from the queue
* Update example to test and showcase new APIs
Allows callers to track if their function is currently in the queue or has finished executing (no longer in the queue or running). Also allows callers to remove the function from the queue if it is no longer needed to run.
* Build and run `runqueue/example` on QtPy ESP32s3 and ensure it works.

feat(runqueue): Add id for tracking function execution

---

components/motorgo-mini/CMakeLists.txt
components/motorgo-mini/Kconfig
components/motorgo-mini/example/main/motorgo_mini_example.cpp
components/motorgo-mini/include/motorgo-mini.hpp
components/motorgo-mini/src/button.cpp
components/motorgo-mini/src/motorgo-mini.cpp

Replace `espp::Button` with use of `espp::Interrupt` to better mirror other BSP compoennts.
Using interrupt provides both the ability to read the state as well as register callback when the state changes. Using the `interrupt` class for this instead of the `button` class allows the user to register additional interrupts should they like, without needing to spawn additional tasks.

feat(motorgo-mini): Replace use of `espp::Button` with `espp::Interrupt`

---

components/math/include/vector2d.hpp

* If `T` is floating point, then enable angle method to get angle between the two vectors.
Consolidates code for computing angle, reducing chances of error and code duplication
Building and running as part of https://github.com/finger563/esp-motorgo-mini-gesture-control

feat(vector): Add angle method to get angle between two vectors

---

components/math/example/main/math_example.cpp
components/math/include/vector2d.hpp

* Add aditional methods
* Update example to test all the new methods
Improves usability of the vector class
Build and run math/example

feat(vector2d): Add `signed_angle` and `inv_magnitude` methods

---

components/display/include/display.hpp
components/esp-box/example/main/esp_box_example.cpp
components/esp-box/include/esp-box.hpp
components/esp-box/src/video.cpp
components/matouch-rotary-display/include/matouch-rotary-display.hpp
components/matouch-rotary-display/src/matouch-rotary-display.cpp
components/seeed-studio-round-display/example/main/seeed_studio_round_display_example.cpp
components/seeed-studio-round-display/include/seeed-studio-round-display.hpp
components/seeed-studio-round-display/src/seeed-studio-round-display.cpp
components/t-deck/include/t-deck.hpp
components/t-deck/src/t-deck.cpp
components/t-dongle-s3/include/t-dongle-s3.hpp
components/t-dongle-s3/src/t-dongle-s3.cpp
components/wrover-kit/include/wrover-kit.hpp
components/wrover-kit/src/wrover-kit.cpp

This change removes the update task entirely from the display component, as lvgl can now retrieve its own task ticks.
It also sets the delay callback, so that it can actually delay, rather than doing [this](https://github.com/lvgl/lvgl/blob/7f07a129e8d77f4984fff8e623fd5be18ff42e74/src/tick/lv_tick.c#L89-L97).
This should be much more efficient.
Potential downside is that the pause and resume functions can no longer do anything.
The user could still "pause" lvgl by not calling `lv_timer_handler()`.
General performance improvements. On programs that actually have a lot of tasks running, the delay callback should free up quite some cpu time.
Tested on the Lilygo T-Encoder-Pro and Smartknob-HA.

feat(display): Remove display task to instead have lvgl handle it directly

---

components/motorgo-mini/include/motorgo-mini.hpp
components/motorgo-mini/src/motorgo-mini.cpp
components/mt6701/include/mt6701.hpp

* Update MT6701 to allow accumulator to be reset
* Update MotorGo Mini to wrap this function for ease of use
This is helpful when switching regimes between velocity control and angle control for instance.
* Build and run as part of the `esp-motorgo-mini-gesture-control` project.

feat(motorgo): Update to allow encoder accumulator to be reset

---

components/bldc_driver/include/bldc_driver.hpp
components/motorgo-mini/example/main/motorgo_mini_example.cpp
components/motorgo-mini/include/motorgo-mini.hpp
components/motorgo-mini/src/motorgo-mini.cpp

* Update the MotorGoMini to use `shared_ptr` for encoders, drivers, and motors. Only allocate them if the relevant functions are called, so that if the user does not want to use them they don't have to waste memory on them.
* Update MotorGoMini to allow the user to pass in motor configuration structs to support a wider variety of use-cases with different and possibly asymmetric motors. This also allows custom PID configurations to be provided.
Allows more modular and varied use of the MotorGoMini class for the motorgo mini hardware.
* Building and running `motorgo-mini/example` on motorgo mini hardware with two motors.
* Building and running within the `finger563/esp-motorgo-mini-gesture-control` project

feat(motorgo-mini): API update - allow motor configuration and only pay for what you use

---

components/i2c/include/i2c.hpp

* Update `I2c::probe` to use `config_.timeout_ms` to determine number of ticks for i2c transaction timeout instead of hardcoded 1000 ticks.
Ensures the configured i2c timeout is used properly when probing the bus, instead of a hardcoded timeout
* Build and run `i2c/example` on ESP32S3 and ensure it probes the bus quickly as it should (~1 second total for all addresses)

fix(i2c): Fix `I2c::probe` timeout not using configured timeout

---

components/ads7138/example/main/ads7138_example.cpp
components/ads7138/include/ads7138.hpp
components/tla2528/example/main/tla2528_example.cpp
components/tla2528/include/tla2528.hpp

* Add new calibrate function to TLA2528, with option to automatically calibrate on construction (default = false).
* Update example to better support hardware to test / show use of other TLA addresses - automatically finding the TLA on the I2C bus.
* Update example to test calibration function and print out the calibration time for reference.
Allows users to gain better precision in adc measurements by calibrating the sensor.
Build and run `tla2528/example` on ESP32-S3 with TLA2528 at address 0x16 on I2C pins 17,18.

feat(tla2528/ads7138): Add `calibrate` function to `TLA2528` and `ADS7138`

---

components/joystick/include/joystick.hpp
components/joystick/src/joystick.cpp
components/math/include/vector2d.hpp

* Update `espp::Vector2d` and `espp::Joystick` to return const references where possible
Reduces the amount of unnecessary copies in application code
Build and run `math/example` and `joystick/example`

feat(joystick/vector): Update to return `const ref` where possible

---

.github/workflows/upload_components.yml

Set dry run to be true if it is not a release, false if it is a release. Should ensure that it is set to false when we actually run a release.

fix(ci): Fix upload on release to not be dry-run

---

components/math/example/main/math_example.cpp
components/math/include/range_mapper.hpp

* Fix issue in range mapper which could occur if the center and range deadzones overlapped
* More explicitly allow uni-directional output mappings when min==center or max==center
* Flesh out test cases for floating point precision issues and values around the deadbands
It was found that the output could be discontinuous if the center deadzone overlapped with one of the range deadzones. The solution was to better handle the case that there are unidirectional output distributions (e.g. where center==min or center==max) and to better handle how the deadbands are calculated.
Before:
Build and run `math/example` on QtPy ESP32s3 and ensure the output of `rm4` matches what we expect.
After:

fix(math): Fix range mapper deadband logic

---

.gitmodules
components/file_system/CMakeLists.txt

* Update `file_system/CMakeLists.txt` to have `littlefs` be the dependency name, since that is what it will be when used as a managed component
* Update `esp_littlefs` submodule to be named `littlefs` so that it matches the managed component behavior.
It was found in testing that the file_system component failed to buid when used as a managed component because the `littlfs` dependency comes in under the name `littlefs`, but the repo was originally designed to use `esp_littlefs`. 
> Note: I tried initially to add the following code to the file system cmake, but it didn't work in the case that `IDF_COMPONENT_MANAGER=0` when building:
```cmake
idf_build_get_property(build_components BUILD_COMPONENTS)
if(file_system IN_LIST build_components)
set(required_littlefs_name esp_littlefs) # Local …
```

fix(file_system): rename `esp_littlefs` submodule to `littlefs` so dependency name is always the same

---

components/wifi/example/main/wifi_example.cpp
components/wifi/include/wifi_ap.hpp
components/wifi/include/wifi_sta.hpp

* Store returned pointer from `esp_netif_create_default_wifi_sta/ap`
* Ensure pointer is freed in destructor
Closes #430
Build and run `wifi/example` on QtPy ESP32s3

fix(wifi) Ensure esp_netif_t* is freed in destructor

---

components/monitor/CMakeLists.txt
components/monitor/example/main/monitor_example.cpp
components/monitor/include/heap_monitor.hpp
components/monitor/src/heap_monitor.cpp
doc/Doxyfile
doc/en/monitor.rst

* Add `HeapMonitor` class to `monitor` component
* Update `monitor/example` to test the HeapMonitor APIs
In addition to tracking task memory / utilization (which the `monitor` component currently does), it is frequently useful to track system memory utilization in various memory regions (e.g. DRAM, SPIRAM, and DMA memories). This PR adds functionality to simplify and make more consistent code which does that.
Build and run `monitor/example` on QtPy ESP32s3

feat(monitor): Add HeapMonitor class to `monitor` component

---

components/file_system/idf_component.yml

* Update `littlefs` submodule to v1.19.2 ref
* Update `file_system` dependency to point to `littlefs: 1.19.2`
Keeps our submodule / dependency up to date, bringing in bugfixes and performance improvements.
https://github.com/joltwallet/esp_littlefs/compare/v1.16.2...v1.19.2
Build and run `file_system/example` on QtPy ESP32s3.

feat(file_system): Update `littlefs` dep to 1.19.2 from 1.16.2

---

components/ble_gatt_server/idf_component.yml
components/gfps_service/idf_component.yml
components/hid_service/idf_component.yml

Update `esp-nimble-cpp` to 2.3.0
Keeps our dependencies up to date, adding new features and bugfixes to the BLE component.
https://github.com/h2zero/esp-nimble-cpp/compare/2.2.1...2.3.0

chore: Update esp-nimble-cpp dep to 2.3.0

---

components/bldc_haptics/example/main/bldc_haptics_example.cpp
components/bldc_haptics/include/bldc_haptics.hpp

* Update `BldcHaptics` to take in `std::shared_ptr` instead of `std::reference_wrapper` for more consistency with existing motor and BSP APIs.
* Ensures easier use of the component with other BSP components.
Note: while this is technically a breaking API change, I'm actually going to treat this as a fix as it makes it more consistent with the rest of the motor APIs.
* Build `bldc_haptics/example`

feat(bldc_haptics): Update to use shared_ptr instead of reference_wrapper

---

components/motorgo-mini/src/motorgo-mini.cpp

* Change from polling to interrupt based synchronous SPI device read
Improves performance of motorgo mini code and reduces processor utilization
Building and running `motorgo-mini/example` on MotorGo Mini hardware.

feat(motorgo_mini): Update encoder read to use interrupt

---

components/wifi/CMakeLists.txt
components/wifi/example/main/wifi_example.cpp
components/wifi/idf_component.yml
components/wifi/include/wifi_ap.hpp
components/wifi/include/wifi_ap_menu.hpp
components/wifi/include/wifi_sta.hpp
components/wifi/include/wifi_sta_menu.hpp
doc/Doxyfile
doc/en/wifi/wifi_ap.rst
doc/en/wifi/wifi_sta.rst

* Add configuration / query methods to both AP and STA
* Add `wifi_ap_menu` and `wifi_sta_menu` for easy configuration / control of WiFi AP/STA using CLI
* Fix bug in event registration in both AP and STA
* Update example to use menus (if compiled with CXX exceptions)
* Update docs accordingly
Fleshes out AP and STA to be more useful, supporting easier configuration and better support for stored security usage.
Build and run `wifi/example` on QtPy ESP32s3

feat(wifi): Flesh out AP + STA and add menus for control/config

---

components/rtsp/include/rtsp_client.hpp
components/rtsp/include/rtsp_server.hpp
components/rtsp/include/rtsp_session.hpp
components/rtsp/src/rtsp_client.cpp
components/rtsp/src/rtsp_server.cpp
components/rtsp/src/rtsp_session.cpp
components/socket/src/tcp_socket.cpp
components/socket/src/udp_socket.cpp

* Ensure receive timeout is set on RtspClient's `rtp_socket` and `rtcp_socket`, so that the receive will return and their receive tasks can be stopped. Otherwise the destructors will never complete and the calling context will block indefinitely.
* Fix default rtcp port to ensure it's actually `5001` (matching docs)
* Allow timeouts for all receive/accept sockets, and ensure they are configurable (with defaults for backwards compatibility)
* Update logging to reduce log level for expected types of error codes (e.g. timeout on socket receive / accept)
Fixes an issue which prevented the RtspClient from being able to be destroyed.
Build and run as part of the [camera-display](https://github.com/esp-cpp/camera-display) project and ensure that the wifi can be disconnected and then reconnected …

fix(rtsp): Fix issue preventing client destructor from completing

---

components/ble_gatt_server/example/sdkconfig.defaults.esp32s3
components/drv2605/CMakeLists.txt
components/drv2605/example/main/drv2605_example.cpp
components/drv2605/example/sdkconfig.defaults.esp32s3
components/drv2605/idf_component.yml
components/drv2605/include/drv2605_menu.hpp
doc/Doxyfile
doc/en/haptics/drv2605.rst

* Add `espp::Drv2605Menu` and use it in example if exceptions are enabled
* Update docs accordingly
* Add CLI dep to `drv2605`
Makes it easier to test various motors and configurations of the driver and ensure the APIs all work / implementation is valid.
Build and run `drv2605/example` with exceptions enabled on a QtPy ESP32s3

feat(drv2605): Add CLI menu for configuring/testing DRV2605

---

.gitmodules

* Switch submodule `google/nearby` to be `esp-cpp/nearby` at tag `espp-v1.0.12` which is the same commit we were at in google/nearby
Related to #466, we need some additional events / callbacks to fully support subsequent pairing.
This will allow us to more easily add changes to the nearby library and integrate them with our systems.
- As part of #466.
- Building in CI to ensure nothing breaks

feat(gfps): Switch to using esp-cpp/nearby (fork of google/nearby)

---

components/esp-box/example/main/esp_box_example.cpp
components/ws-s3-touch/example/main/ws_s3_touch_example.cpp

This PR ensures that the gravity vectors always point down, even if the user presses the on-screen button to rotate the screen to 90, 180, or 270 degrees.

fix(examples): Update `esp-box/example` and `ws-s3-touch/example` so that the gravity vector always points down regardless of screen rotation

---

components/ws-s3-lcd-1-47/include/ws-s3-lcd-1-47.hpp
components/ws-s3-lcd-1-47/src/ws-s3-lcd-1-47.cpp

feat(ws-s3-lcd-1-47): Update backlight to be initialized by LCD instead of display

---

components/ws-s3-geek/include/ws-s3-geek.hpp
components/ws-s3-geek/src/ws-s3-geek.cpp

feat(ws-s3-geek): Backlight is available after initialize_lcd now

---

components/file_system/example/main/file_system_example.cpp
components/file_system/src/file_system.cpp

* Return early from `espp::FileSystem::remove(path, error_code)` if the `path` does not exist (error_code is set by `std::filesystem::status`).
* Add check to example for ensuring fale/error_code are properlyset when trying to remove a non-existent file.
* Adds a missing check for completeness to `espp::FileSystem::remove(path, error_code)`.
* Ensures the code doesn't attempt to remove a file that doesn't exist, which could lead to unnecessary error handling.
* Build and run `file_system/example` on qtpy esp32s3
- [] I have added tests to cover my changes.

feat(file_system): Return early from remove() if path does not exist

---

components/joystick/example/main/joystick_example.cpp
components/led/src/led.cpp
components/math/example/CMakeLists.txt
components/math/example/main/math_example.cpp
components/math/include/fast_math.hpp
components/math/include/gaussian.hpp

- Explicitly use `float` for floating-point literals to avoid implicit double to float conversions
- Use `expf` instead of `exp` for better performance with `float` types
- Turn on warning flags for implicit conversions in math example
- Fix implicit conversion warnings in math and joystick examples
- Ensure we're not accidentally using double precision where float is intended, which could possibly lead to performance issues
- Compiled and ran math and joystick examples on supported hardware

feat(math): Remove accidental double-promotion from float and turn on warnings in example

---

components/kts1622/example/main/kts1622_example.cpp
components/kts1622/include/kts1622.hpp

- Allow user to specify default output values for output pins on the KTS1622
- Fix documentation (wrong default specified for KTS1622 output drive mode)
- Actually set output drive mode in initialization code
- Update void return functions to return success boolean for simpler / easier error checking.
Ensures that users who want to set outputs do not have possible short glitches in unexpected states during initialization if they are using the config structure to set the direction of the pins.
Build and run main on test hardware.

feat(kts1622): Update `kts1622` to allow initial specification of output values

---

components/pi4ioe5v/example/main/pi4ioe5v_example.cpp
components/pi4ioe5v/include/pi4ioe5v.hpp

- Fix register map for PI4IOE5V component to match (the right) datasheet
- Add additional functions for configuring pull-up/pull-down resistors on GPIO pins
- Add additional functions for reset, chip id, interrupt configuration, and high-impedance mode
Ensures that the `pi45ioe5v` component is correctly implemented according to its datasheet, and provides additional functionality for better control of the GPIO pins.
Note: there are a few different variants of the `pi4ioe5v` expander, but the one I'm specifically targeting this to now is the [PI4IOE5V6408](https://www.diodes.com/datasheet/download/PI4IOE5V6408.pdf) since it's whats in the `m5stack-tab5`.
Build and run as part of a larger BSP (in progress) for the `m5stack-tab5` which uses this component (x2).

fix(pi4ioe5v): Fix component implementation to be correct
